"""initial_schema

Revision ID: 1097d9b3bb73
Revises: 
Create Date: 2026-07-29 00:32:42.138998

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1097d9b3bb73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('crm_webhook_url', sa.Text(), nullable=True),
    sa.Column('crm_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealers_city'), 'dealers', ['city'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicles_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('range_km', sa.Integer(), nullable=True),
    sa.Column('is_empanelled', sa.Boolean(), nullable=False),
    sa.Column('empanelled_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_master_category'), 'vehicles_master', ['category'], unique=False)
    op.create_index(op.f('ix_vehicles_master_model'), 'vehicles_master', ['model'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=True),
    sa.Column('message_role', sa.String(length=10), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_conversation_id'), 'ai_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('battery_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_model_id', sa.UUID(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('battery_score', sa.SmallInteger(), nullable=True),
    sa.Column('remaining_life_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('certificate_valid_until', sa.Date(), nullable=True),
    sa.Column('qr_code', sa.String(length=64), nullable=True),
    sa.Column('s3_report_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicles_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_battery_reports_certificate_valid_until'), 'battery_reports', ['certificate_valid_until'], unique=False)
    op.create_index(op.f('ix_battery_reports_owner_id'), 'battery_reports', ['owner_id'], unique=False)
    op.create_table('dealer_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('source_module', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_leads_dealer_id'), 'dealer_leads', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_leads_user_id'), 'dealer_leads', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subsidy_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('registration_state', sa.String(length=20), nullable=True),
    sa.Column('rc_issue_date', sa.Date(), nullable=True),
    sa.Column('filing_deadline', sa.Date(), nullable=True),
    sa.Column('scrappage_tradein', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_calculated', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsidy_applications_status'), 'subsidy_applications', ['status'], unique=False)
    op.create_index(op.f('ix_subsidy_applications_user_id'), 'subsidy_applications', ['user_id'], unique=False)
    op.create_table('subsidy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('year_tier', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price_ceiling', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_approver_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['first_approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsidy_rules_category'), 'subsidy_rules', ['category'], unique=False)
    op.create_index(op.f('ix_subsidy_rules_status'), 'subsidy_rules', ['status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('is_delhi_ncr', sa.Boolean(), nullable=True),
    sa.Column('daily_km', sa.Integer(), nullable=True),
    sa.Column('housing_type', sa.String(length=20), nullable=True),
    sa.Column('parking_socket_access', sa.String(length=10), nullable=True),
    sa.Column('family_size', sa.String(length=20), nullable=True),
    sa.Column('preferred_categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('charging_preference', sa.String(length=10), nullable=True),
    sa.Column('finance_pref', sa.String(length=10), nullable=True),
    sa.Column('emi_comfort', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_subsidy_rules_status'), table_name='subsidy_rules')
    op.drop_index(op.f('ix_subsidy_rules_category'), table_name='subsidy_rules')
    op.drop_table('subsidy_rules')
    op.drop_index(op.f('ix_subsidy_applications_user_id'), table_name='subsidy_applications')
    op.drop_index(op.f('ix_subsidy_applications_status'), table_name='subsidy_applications')
    op.drop_table('subsidy_applications')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_dealer_leads_user_id'), table_name='dealer_leads')
    op.drop_index(op.f('ix_dealer_leads_dealer_id'), table_name='dealer_leads')
    op.drop_table('dealer_leads')
    op.drop_index(op.f('ix_battery_reports_owner_id'), table_name='battery_reports')
    op.drop_index(op.f('ix_battery_reports_certificate_valid_until'), table_name='battery_reports')
    op.drop_table('battery_reports')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_created_at'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_conversation_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_vehicles_master_model'), table_name='vehicles_master')
    op.drop_index(op.f('ix_vehicles_master_category'), table_name='vehicles_master')
    op.drop_table('vehicles_master')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dealers_city'), table_name='dealers')
    op.drop_table('dealers')
    # ### end Alembic commands ###
