import {
  EmpanelledVehicle,
  SubsidyRule,
  Dealer,
  BatteryReport,
  SubsidyApplication,
  UserProfile,
} from '@/types';

export const MOCK_EMPANELLED_VEHICLES: EmpanelledVehicle[] = [
  {
    id: 'veh-2w-ather450x',
    make: 'Ather Energy',
    model: 'Ather 450X',
    variant: 'Gen 3 (3.7 kWh)',
    category: '2W',
    exShowroomPrice: 145000,
    effectivePrice: 126500,
    subsidyAmount: 18500,
    scrappageBonus: 5000,
    rangeKm: 150,
    batteryCapacityKwh: 3.7,
    empanelledStatus: true,
    chargingTimeHours: 4.5,
    topSpeedKmvh: 90,
    features: ['Fast Charging (Grid)', 'Google Maps Navigation', 'Warp Mode', 'AutoHold'],
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    whyThisFits: 'Ideal for daily Delhi urban commutes with fast-charging grid access and proven battery thermal management.',
    runningCostPerKm: 0.25,
  },
  {
    id: 'veh-2w-tvsiqube',
    make: 'TVS',
    model: 'iQube ST',
    variant: 'ST (4.6 kWh)',
    category: '2W',
    exShowroomPrice: 138000,
    effectivePrice: 118000,
    subsidyAmount: 20000,
    scrappageBonus: 5000,
    rangeKm: 145,
    batteryCapacityKwh: 4.6,
    empanelledStatus: true,
    chargingTimeHours: 4.1,
    topSpeedKmvh: 82,
    features: ['7-inch TFT Touchscreen', '32L Underseat Storage', 'Alexa Skill Integration'],
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    whyThisFits: 'Family-friendly seating and massive storage, perfect for daily multi-stop city errands.',
    runningCostPerKm: 0.28,
  },
  {
    id: 'veh-4w-tatanexonev',
    make: 'Tata Motors',
    model: 'Nexon.ev',
    variant: 'Empowered+ Long Range (40.5 kWh)',
    category: '4W',
    exShowroomPrice: 1699000,
    effectivePrice: 1549000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 465,
    batteryCapacityKwh: 40.5,
    empanelledStatus: true,
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['V2L & V2V Charging', 'Arc.ev Connected Car Tech', 'JBL Cinematic Sound System'],
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    whyThisFits: 'Top choice for Delhi-NCR long commutes and weekend trips with 100% Delhi policy tax waiver.',
    runningCostPerKm: 1.10,
  },
  {
    id: 'veh-4w-tatapunchev',
    make: 'Tata Motors',
    model: 'Punch.ev',
    variant: 'Smart+ (25 kWh)',
    category: '4W',
    exShowroomPrice: 1099000,
    effectivePrice: 974000,
    subsidyAmount: 125000,
    scrappageBonus: 15000,
    rangeKm: 315,
    batteryCapacityKwh: 25.0,
    empanelledStatus: true,
    chargingTimeHours: 5.0,
    topSpeedKmvh: 135,
    features: ['acti.ev Dedicated Architecture', 'Paddle Shifters for Regenerative Braking', '10.25-inch Infotainment'],
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    whyThisFits: 'Highest value-for-money compact EV SUV for high daily distance on Delhi roads.',
    runningCostPerKm: 0.90,
  },
  {
    id: 'veh-4w-mgcomet',
    make: 'MG Motor',
    model: 'Comet EV',
    variant: 'Exclusive (17.3 kWh)',
    category: '4W',
    exShowroomPrice: 799000,
    effectivePrice: 712500,
    subsidyAmount: 86500,
    scrappageBonus: 10000,
    rangeKm: 230,
    batteryCapacityKwh: 17.3,
    empanelledStatus: true,
    chargingTimeHours: 3.5,
    topSpeedKmvh: 100,
    features: ['Ultra-Compact Parking Turning Radius (4.2m)', 'Dual 10.25 screens', 'i-SMART Tech'],
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    whyThisFits: 'Easiest car to park and drive through dense Delhi traffic like Chandni Chowk & CP.',
    runningCostPerKm: 0.70,
  },
];

export const MOCK_SUBSIDY_RULES: SubsidyRule[] = [
  {
    policyVersion: 'Delhi EV Policy 2026 (Phase 1)',
    category: '2W',
    yearTier: 1,
    incentivePerKwh: 5000,
    maxCapAmount: 20000,
    scrappageBonusAmount: 5000,
    roadTaxWaiverPct: 100,
    registrationFeeWaiver: true,
    priceCeiling: 150000,
    effectiveFrom: '2026-07-01',
    effectiveTo: '2027-03-31',
  },
  {
    policyVersion: 'Delhi EV Policy 2026 (Phase 1)',
    category: '4W',
    yearTier: 1,
    incentivePerKwh: 10000,
    maxCapAmount: 150000,
    scrappageBonusAmount: 25000,
    roadTaxWaiverPct: 100,
    registrationFeeWaiver: true,
    priceCeiling: 2000000,
    effectiveFrom: '2026-07-01',
    effectiveTo: '2027-03-31',
  },
];

export const MOCK_DEALERS: Dealer[] = [
  {
    id: 'dlr-tata-okhla',
    name: 'AutoVikas Tata EV Zone',
    brand: 'Tata Motors',
    address: 'Plot 14, Okhla Industrial Estate Phase 3',
    locality: 'Okhla',
    city: 'New Delhi',
    rating: 4.8,
    reviewCount: 320,
    distanceKm: 3.2,
    empanelledModels: ['Tata Nexon.ev', 'Tata Punch.ev', 'Tata Tiago.ev'],
    phone: '+91 98100 12345',
    email: 'evsales@autovikas.com',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Free 7.2kW AC Wallbox Charger Installation + ₹10,000 accessories kit',
  },
  {
    id: 'dlr-ather-cp',
    name: 'Ather Space Connaught Place',
    brand: 'Ather Energy',
    address: 'E-Block, Inner Circle, Connaught Place',
    locality: 'Connaught Place',
    city: 'New Delhi',
    rating: 4.9,
    reviewCount: 512,
    distanceKm: 5.6,
    empanelledModels: ['Ather 450X', 'Ather Apex', 'Ather Rizta'],
    phone: '+91 98111 67890',
    email: 'cp@atherspace.in',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Complimentary 1-Year Ather Grid Fast Charging Pass',
  },
  {
    id: 'dlr-mg-gurgaon',
    name: 'Flagship MG EV Studio',
    brand: 'MG Motor',
    address: 'Golf Course Road, Sector 54',
    locality: 'Gurgaon',
    city: 'Delhi-NCR',
    rating: 4.7,
    reviewCount: 189,
    distanceKm: 12.4,
    empanelledModels: ['MG Comet EV', 'MG ZS EV'],
    phone: '+91 98711 43210',
    email: 'contact@mgevstudio.com',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Instant ₹5,000 cash discount on booking through WhyEV',
  },
];

export const MOCK_BATTERY_REPORT: BatteryReport = {
  id: 'bat-rep-90812',
  vehicleId: 'veh-4w-tatanexonev',
  makeModel: 'Tata Nexon.ev (2024 Model)',
  year: 2024,
  odometerKm: 28450,
  inspectionDate: '2026-07-15',
  batteryScore: 92,
  healthStatus: 'Excellent',
  estimatedRemainingYears: 7.5,
  degradationPct: 3.8,
  chargingCycleCount: 310,
  certificateValidUntil: '2027-01-15',
  qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://whyev.in/verify/bat-rep-90812',
  inspectorName: 'Suresh Kumar (NABL Certified Specialist - TÜV partner)',
};

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-abhishek-77',
  name: 'Abhishek Sharma',
  phone: '+91 98765 43210',
  email: 'abhishek.sharma@example.com',
  city: 'New Delhi',
  isDelhiResident: true,
  housingType: 'apartment',
  hasAssignedParking: true,
  hasHomeCharger: false,
  dailyCommuteKm: 42,
  budgetMin: 800000,
  budgetMax: 1600000,
  familySize: 4,
  preferredCategory: '4W',
  tradeInIceVehicle: true,
  profileCompletionPct: 85,
};

export const MOCK_SUBSIDY_APPLICATION: SubsidyApplication = {
  id: 'sub-app-delhi-2026-041',
  userId: 'usr-abhishek-77',
  vehicleId: 'veh-4w-tatanexonev',
  vehicleModelName: 'Tata Nexon.ev (Long Range)',
  rcIssueDate: '2026-07-10',
  filingDeadline: '2026-08-09',
  status: 'documents_pending',
  calculatedSubsidy: 150000,
  scrappageBonus: 25000,
  taxWaiverEstimated: 125000,
  totalBenefit: 300000,
  submittedAt: undefined,
  daysRemaining: 12,
};
