import {
  EmpanelledVehicle,
  SubsidyRule,
  Dealer,
  BatteryReport,
  SubsidyApplication,
  UserProfile,
  SavedSubsidyReport,
  Review,
} from '@/types';
import { SEEDED_VEHICLES_MASTER, UPCOMING_2026_VEHICLES } from '@/lib/seed/vehiclesMaster';

export const MOCK_2W_VEHICLES: EmpanelledVehicle[] = [
  {
    id: 'veh-2w-ather450x',
    make: 'Ather Energy',
    model: 'Ather 450X',
    variant: 'Gen 3 (3.7 kWh)',
    category: '2W',
    bodyType: 'Scooter',
    priceMinLakh: 1.45,
    priceMaxLakh: 1.55,
    exShowroomPrice: 145000,
    effectivePrice: 126500,
    subsidyAmount: 18500,
    scrappageBonus: 5000,
    rangeKm: 150,
    batteryCapacityKwh: 3.7,
    empanelledStatus: 'unverified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 90,
    features: ['Fast Charging (Grid)', 'Google Maps Navigation', 'Warp Mode', 'AutoHold'],
    whyThisFits: 'Ideal for daily Delhi urban commutes with fast-charging grid access and proven battery thermal management.',
    runningCostPerKm: 0.25,
    dataSourceDate: '2026-07',
  },
  {
    id: 'veh-2w-tvsiqube',
    make: 'TVS',
    model: 'iQube ST',
    variant: 'ST (4.6 kWh)',
    category: '2W',
    bodyType: 'Scooter',
    priceMinLakh: 1.38,
    priceMaxLakh: 1.48,
    exShowroomPrice: 138000,
    effectivePrice: 118000,
    subsidyAmount: 20000,
    scrappageBonus: 5000,
    rangeKm: 145,
    batteryCapacityKwh: 4.6,
    empanelledStatus: 'unverified',
    chargingTimeHours: 4.1,
    topSpeedKmvh: 82,
    features: ['TFT Touchscreen', 'Alexa Skill Integration', 'Large Underseat Storage', 'Regen Braking'],
    whyThisFits: 'Excellent build quality with spacious storage for family utility and lower per-km charging cost.',
    runningCostPerKm: 0.22,
    dataSourceDate: '2026-07',
  },
];

export const MOCK_EMPANELLED_VEHICLES: EmpanelledVehicle[] = [
  ...MOCK_2W_VEHICLES,
  ...SEEDED_VEHICLES_MASTER,
];

export { UPCOMING_2026_VEHICLES };

export const MOCK_SUBSIDY_RULES: SubsidyRule[] = [
  {
    policyVersion: 'Delhi EV Policy 2026',
    category: '2W',
    yearTier: 1,
    incentivePerKwh: 5000,
    maxCapAmount: 30000,
    scrappageBonusAmount: 5000,
    roadTaxWaiverPct: 100,
    registrationFeeWaiver: true,
    priceCeiling: 200000,
    effectiveFrom: '2026-07-01',
    effectiveTo: '2027-06-30',
  },
  {
    policyVersion: 'Delhi EV Policy 2026',
    category: '4W',
    yearTier: 1,
    incentivePerKwh: 10000,
    maxCapAmount: 150000,
    scrappageBonusAmount: 25000,
    roadTaxWaiverPct: 100,
    registrationFeeWaiver: true,
    priceCeiling: 2000000,
    effectiveFrom: '2026-07-01',
    effectiveTo: '2027-06-30',
  },
];

export const MOCK_DEALERS: Dealer[] = [
  {
    id: 'dlr-tata-okhla',
    name: 'Pragati Tata EV Showroom',
    brand: 'Tata Motors',
    address: 'Plot No. 14, Okhla Industrial Estate Phase 3',
    locality: 'Okhla',
    city: 'New Delhi',
    rating: 4.8,
    reviewCount: 312,
    distanceKm: 4.2,
    empanelledModels: ['Nexon EV', 'Punch EV', 'Sierra EV', 'Curvv EV', 'Tiago EV'],
    phone: '+91 11 4050 9900',
    email: 'evsupport@pragatitata.com',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Free 7.2 kW Wallbox Charger Installation included',
  },
  {
    id: 'dlr-ather-saket',
    name: 'Ather Space Experience Centre',
    brand: 'Ather Energy',
    address: 'Community Centre, Saket District Centre',
    locality: 'Saket',
    city: 'New Delhi',
    rating: 4.9,
    reviewCount: 480,
    distanceKm: 6.8,
    empanelledModels: ['Ather 450X', 'Ather Rizta'],
    phone: '+91 11 4122 8811',
    email: 'saket@atherspace.com',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Complimentary 1-Year Ather Grid Fast Charging Pass',
  },
  {
    id: 'dlr-mg-connaught',
    name: 'Flagship MG EV Experience Centre',
    brand: 'MG Motor',
    address: 'Inner Circle, Connaught Place',
    locality: 'Connaught Place',
    city: 'New Delhi',
    rating: 4.7,
    reviewCount: 220,
    distanceKm: 11.5,
    empanelledModels: ['Windsor EV', 'ZS EV', 'Comet EV'],
    phone: '+91 11 2341 7766',
    email: 'cp@mgmotor.in',
    isVerified: true,
    hasInventoryLive: true,
    exclusiveOffer: 'Zero Processing Fee & 1-Year Insurance Discount',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    targetType: 'dealer',
    targetId: 'dlr-tata-okhla',
    targetName: 'Pragati Tata EV Showroom (Okhla)',
    userId: 'usr-rohan-01',
    userName: 'Rohan Mehta',
    userCity: 'Saket, Delhi',
    rating: 5,
    text: 'Test drive experience was completely transparent. Showroom staff walked me through the 30-day post-RC Delhi EV Policy 2026 application without any aggressive sales calls.',
    createdAt: '2026-07-22',
    verifiedInteractionId: 'app-tata-okhla-901',
    status: 'published',
  },
  {
    id: 'rev-002',
    targetType: 'charging_station',
    targetId: 'stn-tata-cp',
    targetName: 'Tata Power EZ Charge (Connaught Place)',
    userId: 'usr-pooja-02',
    userName: 'Pooja Verma',
    userCity: 'Dwarka, Delhi',
    rating: 5,
    text: 'Both 60 kW CCS2 guns were functional! Charged my Nexon EV from 20% to 80% in 34 minutes while having coffee nearby. Uptime score on WhyEV was 100% accurate.',
    createdAt: '2026-07-24',
    verifiedInteractionId: 'chg-rep-cp-882',
    status: 'published',
  },
  {
    id: 'rev-003',
    targetType: 'dealer',
    targetId: 'dlr-ather-saket',
    targetName: 'Ather Space (Saket)',
    userId: 'usr-vikram-03',
    userName: 'Vikram Singh',
    userCity: 'Rohini, Delhi',
    rating: 5,
    text: 'Seamless doorstep test drive booking. They honored the 1-year Ather Grid charger offer listed on WhyEV directly.',
    createdAt: '2026-07-25',
    verifiedInteractionId: 'app-ather-saket-441',
    status: 'published',
  },
  {
    id: 'rev-004',
    targetType: 'charging_station',
    targetId: 'stn-statiq-saket',
    targetName: 'Statiq Hub (Select CITYWALK)',
    userId: 'usr-ananya-04',
    userName: 'Ananya Roy',
    userCity: 'Vasant Kunj, Delhi',
    rating: 4,
    text: 'Clean charging bay with active security. 30 kW charger worked smoothly. Slight waiting time during weekend peak hours.',
    createdAt: '2026-07-26',
    verifiedInteractionId: 'chg-rep-saket-712',
    status: 'published',
  },
];

export const MOCK_BATTERY_REPORT: BatteryReport = {
  id: 'bat-rep-90812',
  vehicleId: 'tata-nexon-ev',
  makeModel: 'Tata Nexon EV (Empowered+ 45)',
  year: 2024,
  odometerKm: 28450,
  inspectionDate: '2026-07-15',
  batteryScore: 92,
  healthStatus: 'Excellent',
  estimatedRemainingYears: 7.5,
  degradationPct: 3.8,
  chargingCycleCount: 310,
  certificateValidUntil: '2027-01-15',
  qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://whyev.in/verify/bat-rep-90812',
  inspectorName: 'Suresh Kumar (NABL Certified Specialist - TÜV partner)',
};

export const MOCK_SAVED_SUBSIDY_REPORTS: SavedSubsidyReport[] = [
  {
    id: 'rep-sub-2026-001',
    vehicleName: 'Tata Nexon EV (Empowered+ 45)',
    state: 'Delhi',
    estimatedSavings: 300000,
    dateGenerated: '2026-07-20',
    batteryCapacityKwh: 45,
    scrappageIncluded: true,
  },
  {
    id: 'rep-sub-2026-002',
    vehicleName: 'Ather 450X Gen 3',
    state: 'Delhi',
    estimatedSavings: 23500,
    dateGenerated: '2026-07-25',
    batteryCapacityKwh: 3.7,
    scrappageIncluded: true,
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-aishwarya-2026',
  name: 'Aishwarya Sharma',
  phone: '+91 98765 43210',
  email: 'aishwarya@example.com',
  state: 'Delhi',
  city: 'New Delhi',
  memberSince: 'July 2026',
  isDelhiResident: true,
  housingType: 'apartment',
  hasAssignedParking: true,
  hasHomeCharger: false,
  dailyCommuteKm: 42,
  budgetMin: 800000,
  budgetMax: 1800000,
  familySize: 4,
  preferredCategory: '4W',
  tradeInIceVehicle: true,
  profileCompletionPct: 85,
  savedReports: MOCK_SAVED_SUBSIDY_REPORTS,
};

export const MOCK_SUBSIDY_APPLICATION: SubsidyApplication = {
  id: 'sub-app-delhi-2026-041',
  userId: 'usr-aishwarya-2026',
  vehicleId: 'tata-nexon-ev',
  vehicleModelName: 'Tata Nexon EV (Empowered+ 45)',
  rcIssueDate: '2026-07-10',
  filingDeadline: '2026-08-09',
  status: 'documents_pending',
  calculatedSubsidy: 150000,
  scrappageBonus: 25000,
  taxWaiverEstimated: 125000,
  totalBenefit: 300000,
  submittedAt: undefined,
  daysRemaining: 12,
};

export const MOCK_SUBSIDY_APPLICATIONS: SubsidyApplication[] = [
  MOCK_SUBSIDY_APPLICATION,
];

export const MOCK_CHARGING_STATIONS = [
  {
    id: 'stn-tata-cp',
    name: 'Tata Power EZ Charge - Connaught Place',
    latitude: 28.6315,
    longitude: 77.2167,
    address: 'Outer Circle, Connaught Place',
    city: 'New Delhi',
    connectorTypes: ['CCS2', 'Type 2 AC'],
    chargingSpeedKw: 60,
    availabilityStatus: 'available' as const,
    workingStatus: 'Operational (2/2 Guns Active)',
    pricingPerKwh: 18,
    operatingHours: '24/7 Open',
    amenities: ['Coffee Shop', 'Washrooms', 'Shopping Mall', 'Covered Bay'],
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80'],
    lastUpdated: '5 mins ago',
  },
  {
    id: 'stn-statiq-saket',
    name: 'Statiq Fast Charging Hub - Select CITYWALK',
    latitude: 28.5286,
    longitude: 77.2195,
    address: 'P1 Parking, Select CITYWALK Mall, Saket',
    city: 'New Delhi',
    connectorTypes: ['CCS2', 'GB/T'],
    chargingSpeedKw: 120,
    availabilityStatus: 'available' as const,
    workingStatus: 'Operational (4/4 Guns Active)',
    pricingPerKwh: 20,
    operatingHours: '09:00 AM - 11:00 PM',
    amenities: ['Mall Access', 'Valet Parking', 'Food Court', 'Security'],
    images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop&q=80'],
    lastUpdated: '12 mins ago',
  },
];

export const MOCK_NEWS_ARTICLES = [
  {
    id: 'art-1',
    slug: 'delhi-ev-policy-2026-subsidy-guide',
    title: 'Delhi EV Policy 2026: Complete Direct Subsidy & Road Tax Exemption Guide',
    image: '/explore/curvv-ev-desktop.png',
    summary: 'Everything EV buyers need to know about the extended Delhi state subsidies, 30-day filing timeline post-RC, and scrappage bonuses.',
    content: 'The Delhi Government has officially notified the Delhi EV Policy 2026, offering up to ₹1,50,000 direct bank transfer subsidies for electric cars and 100% road tax waiver...',
    author: 'Vikram Sharma',
    source: 'WhyEV Policy Desk',
    readTime: '4 min read',
    publishedDate: '01 August 2026',
    category: 'Policy & Subsidies',
    tags: ['Delhi EV Policy', 'Direct Subsidy', 'PM E-DRIVE'],
    isFeatured: true,
  },
  {
    id: 'art-2',
    slug: 'tata-curvv-ev-real-world-range-test',
    title: 'Tata Curvv EV Real-World Highway Range Test: 450 km Delivered?',
    image: '/explore/curvv-ev-desktop.png',
    summary: 'We tested the 55 kWh Tata Curvv EV on the Yamuna Expressway under summer conditions with full air conditioning to measure true range.',
    content: 'Claimed range specifications often vary from highway reality. In our test from Noida to Agra, the Curvv EV achieved 412 km on a single charge...',
    author: 'Rohan Gupta',
    source: 'WhyEV Tech Lab',
    readTime: '6 min read',
    publishedDate: '28 July 2026',
    category: 'Reviews & Tests',
    tags: ['Tata Curvv EV', 'Real World Range', 'Battery Test'],
    isFeatured: false,
  },
];

