import { EmpanelledVehicle } from '@/types';

export interface UpcomingVehicle {
  make: string;
  model: string;
  note: string;
}

export const UPCOMING_2026_VEHICLES: UpcomingVehicle[] = [
  { make: 'Toyota', model: 'Urban Cruiser EV', note: 'e-Vitara-based mid-size EV SUV' },
  { make: 'Mahindra', model: 'XEV 9e', note: 'Born-electric coupe SUV' },
  { make: 'Tata Motors', model: 'Sierra EV', note: 'Iconic SUV reborn on Acti.ev+ platform' },
  { make: 'Citroën', model: 'eC3 Aircross EV', note: 'Versatile 7-seater electric crossover' },
  { make: 'VinFast', model: 'VF3', note: 'Ultra-compact urban electric vehicle' },
  { make: 'Tesla', model: 'Model 3', note: 'Global bestseller arriving in India' },
];

export const SEEDED_VEHICLES_MASTER: EmpanelledVehicle[] = [
  // =====================================
  // TATA MOTORS
  // =====================================
  {
    id: 'tata-tiago-ev',
    make: 'Tata Motors',
    model: 'Tiago EV',
    variant: 'XZ+ Tech Lux (24 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 7.99,
    priceMaxLakh: 11.89,
    exShowroomPrice: 799000,
    effectivePrice: 624000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 315,
    rangeKmClaimedOptions: [250, 315],
    batteryCapacityKwh: 24,
    batteryKwhOptions: [19.2, 24],
    empanelledStatus: 'verified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 120,
    features: ['Multi-mode Regen', 'ZConnect Connected Car', 'Smartwatch Integration'],
    whyThisFits: 'Ultra-accessible urban electric hatchback perfect for city commutes.',
    runningCostPerKm: 0.32,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
    availableVariants: [
      { id: 'tiago-xe-mr', name: 'XE Medium Range (19.2 kWh)', exShowroomPrice: 799000, batteryCapacityKwh: 19.2, claimedRangeKm: 250, features: ['Automated Drive', 'Climate Control', 'ABS with EBD'] },
      { id: 'tiago-xt-mr', name: 'XT Medium Range (19.2 kWh)', exShowroomPrice: 899000, batteryCapacityKwh: 19.2, claimedRangeKm: 250, features: ['Harman Infotainment', 'Smartwatch Connectivity', 'Reverse Camera'] },
      { id: 'tiago-xz-lr', name: 'XZ+ Long Range (24 kWh)', exShowroomPrice: 999000, batteryCapacityKwh: 24.0, claimedRangeKm: 315, features: ['Fast AC Charging', 'Fog Lamps', 'Rain Sensing Wipers'] },
      { id: 'tiago-xz-lux-lr', name: 'XZ+ Tech Lux Long Range (24 kWh)', exShowroomPrice: 1189000, batteryCapacityKwh: 24.0, claimedRangeKm: 315, features: ['Contrast Roof', 'Leatherette Seats', 'Cooling Glovebox'] },
    ],
  },
  {
    id: 'tata-tigor-ev',
    make: 'Tata Motors',
    model: 'Tigor EV',
    variant: 'XZ+ (26 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 12.49,
    priceMaxLakh: 13.75,
    exShowroomPrice: 1249000,
    effectivePrice: 1074000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 315,
    rangeKmClaimedOptions: [315],
    batteryCapacityKwh: 26,
    batteryKwhOptions: [26],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.0,
    topSpeedKmvh: 120,
    features: ['7" Touchscreen Infotainment', 'Automatic Climate Control', 'Dual Airbags'],
    whyThisFits: 'Spacious electric compact sedan suited for family transport.',
    runningCostPerKm: 0.35,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
    availableVariants: [
      { id: 'tigor-xe', name: 'XE (26 kWh)', exShowroomPrice: 1249000, batteryCapacityKwh: 26.0, claimedRangeKm: 315, features: ['LED DRLs', 'Climate Control', 'Dual Airbags'] },
      { id: 'tigor-xm', name: 'XM (26 kWh)', exShowroomPrice: 1299000, batteryCapacityKwh: 26.0, claimedRangeKm: 315, features: ['4 Speakers Audio', 'Keyless Entry', 'Rear Sensors'] },
      { id: 'tigor-xz-plus', name: 'XZ+ (26 kWh)', exShowroomPrice: 1375000, batteryCapacityKwh: 26.0, claimedRangeKm: 315, features: ['7" Touchscreen', 'Push Button Start', 'Reverse Camera'] },
    ],
  },
  {
    id: 'tata-punch-ev',
    make: 'Tata Motors',
    model: 'Punch EV',
    variant: 'Empowered+ LR (35 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 10.99,
    priceMaxLakh: 15.49,
    exShowroomPrice: 1099000,
    effectivePrice: 924000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 421,
    rangeKmClaimedOptions: [315, 421],
    batteryCapacityKwh: 35,
    batteryKwhOptions: [25, 35],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 140,
    features: ['acti.ev Architecture', '10.25" Cinematic Screen', '360° Camera'],
    whyThisFits: 'High ground clearance sub-compact SUV built on acti.ev platform.',
    runningCostPerKm: 0.42,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
    availableVariants: [
      { id: 'punch-smart-mr', name: 'Smart Medium Range (25 kWh)', exShowroomPrice: 999000, batteryCapacityKwh: 25.0, claimedRangeKm: 315, features: ['LED Headlamps', 'Multi-mode Regen', 'ESP'] },
      { id: 'punch-adventure-mr', name: 'Adventure Medium Range (25 kWh)', exShowroomPrice: 1099000, batteryCapacityKwh: 25.0, claimedRangeKm: 315, features: ['Touchscreen', 'Sequential Indicators', 'Jewel Control Knob'] },
      { id: 'punch-adventure-lr', name: 'Adventure Long Range (35 kWh)', exShowroomPrice: 1299000, batteryCapacityKwh: 35.0, claimedRangeKm: 421, features: ['Fast AC Charger Support', 'Electronic Parking Brake', 'Hill Descent Control'] },
      { id: 'punch-empowered-lr', name: 'Empowered+ Long Range (35 kWh)', exShowroomPrice: 1549000, batteryCapacityKwh: 35.0, claimedRangeKm: 421, features: ['10.25" Cinematic Screen', '360° Camera', 'Ventilated Front Seats'] },
    ],
  },
  {
    id: 'tata-nexon-ev',
    make: 'Tata Motors',
    model: 'Nexon EV',
    variant: 'Empowered+ 45 (45 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 14.49,
    priceMaxLakh: 19.49,
    exShowroomPrice: 1449000,
    effectivePrice: 1274000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 489,
    rangeKmClaimedOptions: [325, 489],
    batteryCapacityKwh: 45,
    batteryKwhOptions: [30, 45],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.0,
    topSpeedKmvh: 150,
    features: ['V2L & V2V Charging', 'JBL 9-Speaker Audio', 'Ventilated Front Seats'],
    whyThisFits: "India's benchmark electric SUV with long range and fast charging.",
    runningCostPerKm: 0.48,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
    availableVariants: [
      { id: 'nexon-creative-mr', name: 'Creative+ Medium Range (30 kWh)', exShowroomPrice: 1249000, batteryCapacityKwh: 30.0, claimedRangeKm: 325, features: ['LED Light Bars', '10.25" Touchscreen', 'OTA Updates'] },
      { id: 'nexon-fearless-mr', name: 'Fearless+ Medium Range (30 kWh)', exShowroomPrice: 1449000, batteryCapacityKwh: 30.0, claimedRangeKm: 325, features: ['Wireless Charger', 'Sequential LED DRLs', 'Blind Spot Monitor'] },
      { id: 'nexon-fearless-lr', name: 'Fearless Long Range (45 kWh)', exShowroomPrice: 1699000, batteryCapacityKwh: 45.0, claimedRangeKm: 489, features: ['Electronic Parking Brake', 'Auto Dimming IRVM', 'Express Charging'] },
      { id: 'nexon-empowered-lr', name: 'Empowered+ 45 Long Range (45 kWh)', exShowroomPrice: 1949000, batteryCapacityKwh: 45.0, claimedRangeKm: 489, features: ['V2L & V2V Power Output', 'JBL 9-Speaker Audio', 'Ventilated Seats'] },
    ],
  },
  {
    id: 'tata-curvv-ev',
    make: 'Tata Motors',
    model: 'Curvv EV',
    variant: 'Empowered+ A 55 (55 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 17.49,
    priceMaxLakh: 21.99,
    exShowroomPrice: 1749000,
    effectivePrice: 1574000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 585,
    rangeKmClaimedOptions: [502, 585],
    batteryCapacityKwh: 55,
    batteryKwhOptions: [45, 55],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 160,
    features: ['Flush Door Handles', 'Panoramic Sunroof', 'Level 2 ADAS Suite'],
    whyThisFits: 'Coupe SUV styling paired with 585 km long range capabilities.',
    runningCostPerKm: 0.52,
    availability: 'available',
    imageUrl: '/explore/curvv-ev-desktop.png',
    availableVariants: [
      { id: 'curvv-creative-45', name: 'Creative 45 (45 kWh)', exShowroomPrice: 1749000, batteryCapacityKwh: 45.0, claimedRangeKm: 502, features: ['Flush Door Handles', '10.25" Touchscreen', 'Drive Modes'] },
      { id: 'curvv-accomplished-55', name: 'Accomplished 55 (55 kWh)', exShowroomPrice: 1925000, batteryCapacityKwh: 55.0, claimedRangeKm: 585, features: ['Panoramic Sunroof', '12.3" Cinematic Touchscreen', 'Power Tailgate'] },
      { id: 'curvv-empowered-55', name: 'Empowered+ A 55 (55 kWh)', exShowroomPrice: 2199000, batteryCapacityKwh: 55.0, claimedRangeKm: 585, features: ['Level 2 ADAS Suite', 'Ventilated Seats', 'Gesture Controlled Tailgate'] },
    ],
  },
  {
    id: 'tata-harrier-ev',
    make: 'Tata Motors',
    model: 'Harrier EV',
    variant: 'Dual Motor AWD (60 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 22.00,
    priceMaxLakh: 28.00,
    exShowroomPrice: 2200000,
    effectivePrice: 2025000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 500,
    rangeKmClaimedOptions: [500],
    batteryCapacityKwh: 60,
    batteryKwhOptions: [60],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 170,
    features: ['Dual Motor AWD', 'Terrain Response Modes', 'Level 2 ADAS'],
    whyThisFits: 'Premium 5-seater electric SUV engineered with AWD capability.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'tata-sierra-ev',
    make: 'Tata Motors',
    model: 'Sierra EV',
    variant: 'Lounge Edition (65 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 24.00,
    priceMaxLakh: 30.00,
    exShowroomPrice: 2400000,
    effectivePrice: 2225000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 520,
    rangeKmClaimedOptions: [520],
    batteryCapacityKwh: 65,
    batteryKwhOptions: [65],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 165,
    features: ['Signature Rear Alpine Windows', 'Lounge Seating', 'Acti.ev Platform'],
    whyThisFits: 'Legendary Sierra design revived as a flagship luxury electric SUV.',
    runningCostPerKm: 0.68,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'tata-avinya',
    make: 'Tata Motors',
    model: 'Avinya',
    variant: 'EMEA Flagship (80 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 35.00,
    priceMaxLakh: 45.00,
    exShowroomPrice: 3500000,
    effectivePrice: 3325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 600,
    rangeKmClaimedOptions: [600],
    batteryCapacityKwh: 80,
    batteryKwhOptions: [80],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 180,
    features: ['Gen-3 EMA Architecture', 'Ultra-fast Charging in 30 mins', 'Aroma Diffuser'],
    whyThisFits: 'Next-generation luxury electric vehicle redefining interior space.',
    runningCostPerKm: 0.75,
    availability: 'available',
    imageUrl: '/explore/curvv-ev-desktop.png',
  },

  // =====================================
  // MAHINDRA
  // =====================================
  {
    id: 'mahindra-xev-9e',
    make: 'Mahindra',
    model: 'XEV 9e',
    variant: 'Pack THREE (79 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 21.90,
    priceMaxLakh: 26.50,
    exShowroomPrice: 2190000,
    effectivePrice: 2015000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 656,
    rangeKmClaimedOptions: [535, 656],
    batteryCapacityKwh: 79,
    batteryKwhOptions: [59, 79],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 200,
    features: ['Triple 12.3" Screen Setup', 'INGLO Architecture', '16-Speaker Harman Kardon'],
    whyThisFits: 'Born-electric luxury coupe SUV with impressive 656 km range.',
    runningCostPerKm: 0.58,
    availability: 'available',
    imageUrl: '/explore/be6-desktop.png',
    availableVariants: [
      { id: 'xev9e-pack1', name: 'Pack One (59 kWh)', exShowroomPrice: 2190000, batteryCapacityKwh: 59.0, claimedRangeKm: 542, features: ['Triple Screen Layout', 'MAIA AI Assistant', 'Level 2 ADAS'] },
      { id: 'xev9e-pack2', name: 'Pack Two (79 kWh)', exShowroomPrice: 2490000, batteryCapacityKwh: 79.0, claimedRangeKm: 656, features: ['Harman Kardon Dolby Atmos', 'Ventilated Massage Seats', 'Adaptive Suspension'] },
      { id: 'xev9e-pack3', name: 'Pack Three (79 kWh)', exShowroomPrice: 2650000, batteryCapacityKwh: 79.0, claimedRangeKm: 656, features: ['AWD Quad Drive', 'Autonomous Park Assist', 'Bi-Directional Charging'] },
    ],
  },
  {
    id: 'mahindra-be6',
    make: 'Mahindra',
    model: 'BE 6',
    variant: 'Pack TWO (59 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 18.90,
    priceMaxLakh: 23.50,
    exShowroomPrice: 1890000,
    effectivePrice: 1715000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 535,
    rangeKmClaimedOptions: [535, 682],
    batteryCapacityKwh: 59,
    batteryKwhOptions: [59, 79],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 200,
    features: ['Futuristic Aero Styling', 'RWD Motor (231 PS)', 'Brembo Calipers'],
    whyThisFits: 'High-performance electric SUV with bold futuristic exterior design.',
    runningCostPerKm: 0.55,
    availability: 'available',
    imageUrl: '/explore/be6-desktop.png',
    availableVariants: [
      { id: 'be6-pack1', name: 'Pack One (59 kWh)', exShowroomPrice: 1890000, batteryCapacityKwh: 59.0, claimedRangeKm: 557, features: ['Dual 12.3 Screen', 'Sonic Suite Audio', 'Drive Modes'] },
      { id: 'be6-pack2', name: 'Pack Two (79 kWh)', exShowroomPrice: 2350000, batteryCapacityKwh: 79.0, claimedRangeKm: 682, features: ['Panoraic Sky Roof', 'HUD Display', 'High Performance E-Motor'] },
      { id: 'be6-pack3', name: 'Pack Three (79 kWh)', exShowroomPrice: 2690000, batteryCapacityKwh: 79.0, claimedRangeKm: 682, features: ['Level 2+ ADAS', 'Infinity Glass Roof', 'Semi-Active Suspension'] },
    ],
  },
  {
    id: 'mahindra-xuv400',
    make: 'Mahindra',
    model: 'XUV400',
    variant: 'EL Pro (39.4 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 15.49,
    priceMaxLakh: 17.69,
    exShowroomPrice: 1549000,
    effectivePrice: 1374000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 456,
    rangeKmClaimedOptions: [375, 456],
    batteryCapacityKwh: 39.4,
    batteryKwhOptions: [34.5, 39.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.0,
    topSpeedKmvh: 150,
    features: ['10.25" Dual Screens', 'Wireless Apple CarPlay', 'Level 1 ADAS'],
    whyThisFits: 'Spacious sub-compact electric SUV with punchy acceleration.',
    runningCostPerKm: 0.45,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
    availableVariants: [
      { id: 'xuv400-ec-pro', name: 'EC Pro (34.5 kWh)', exShowroomPrice: 1549000, batteryCapacityKwh: 34.5, claimedRangeKm: 375, features: ['Dual Zone Climate Control', 'Push Button Start', 'All Disc Brakes'] },
      { id: 'xuv400-el-pro', name: 'EL Pro (39.4 kWh)', exShowroomPrice: 1749000, batteryCapacityKwh: 39.4, claimedRangeKm: 456, features: ['10.25" Touchscreen', 'Wireless Android Auto', 'Sunroof', '6 Airbags'] },
    ],
  },
  {
    id: 'mahindra-xuv-3xo-ev',
    make: 'Mahindra',
    model: 'XUV 3XO EV',
    variant: 'AX7L (35 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 13.90,
    priceMaxLakh: 16.50,
    exShowroomPrice: 1390000,
    effectivePrice: 1215000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 400,
    rangeKmClaimedOptions: [400],
    batteryCapacityKwh: 35,
    batteryKwhOptions: [35],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 145,
    features: ['Panoramic Skyroof', 'Level 2 ADAS', 'Electronic Parking Brake'],
    whyThisFits: 'Feature-packed compact SUV tailored for urban and highway driving.',
    runningCostPerKm: 0.42,
    availability: 'available',
    imageUrl: '/explore/be6-desktop.png',
  },
  {
    id: 'mahindra-be-rall-e',
    make: 'Mahindra',
    model: 'BE Rall-E',
    variant: 'Off-Road Edition (79 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 25.00,
    priceMaxLakh: 30.00,
    exShowroomPrice: 2500000,
    effectivePrice: 2325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 500,
    rangeKmClaimedOptions: [500],
    batteryCapacityKwh: 79,
    batteryKwhOptions: [79],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 190,
    features: ['Rugged Off-Road Body Kit', 'All-Terrain Tires', 'Roof Rack Mounts'],
    whyThisFits: 'Adventure-focused electric SUV engineered for off-road trails.',
    runningCostPerKm: 0.62,
    availability: 'available',
    imageUrl: '/explore/be6-desktop.png',
  },

  // =====================================
  // MG MOTOR
  // =====================================
  {
    id: 'mg-comet-ev',
    make: 'MG Motor',
    model: 'Comet EV',
    variant: 'Exclusive Fast Charge (17.3 kWh)',
    category: '4W',
    bodyType: 'Micro EV',
    priceMinLakh: 6.99,
    priceMaxLakh: 9.40,
    exShowroomPrice: 699000,
    effectivePrice: 524000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 230,
    rangeKmClaimedOptions: [230],
    batteryCapacityKwh: 17.3,
    batteryKwhOptions: [17.3],
    empanelledStatus: 'verified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 105,
    features: ['Dual 10.25" Floating Screens', 'Wireless Android Auto', 'IP67 Battery'],
    whyThisFits: 'Ultra-compact micro EV for tight city parking and daily errands.',
    runningCostPerKm: 0.25,
    availability: 'available',
    imageUrl: '/explore/windsor-desktop.png',
    availableVariants: [
      { id: 'comet-executive', name: 'Executive (17.3 kWh)', exShowroomPrice: 736000, batteryCapacityKwh: 17.3, claimedRangeKm: 230, features: ['Dual 10.25" Screens', 'LED Headlamps', 'Reverse Camera'] },
      { id: 'comet-excite', name: 'Excite (17.3 kWh)', exShowroomPrice: 800000, batteryCapacityKwh: 17.3, claimedRangeKm: 230, features: ['i-SMART Connected Tech', 'Fast Charging Support', 'Keyless Go'] },
      { id: 'comet-exclusive', name: 'Exclusive (17.3 kWh)', exShowroomPrice: 940000, batteryCapacityKwh: 17.3, claimedRangeKm: 230, features: ['Electronic Parking Brake', 'Leatherette Steering', 'Power Folding Mirrors'] },
    ],
  },
  {
    id: 'mg-windsor-ev',
    make: 'MG Motor',
    model: 'Windsor EV',
    variant: 'Essence (38 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 13.50,
    priceMaxLakh: 15.50,
    exShowroomPrice: 1350000,
    effectivePrice: 1175000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 331,
    rangeKmClaimedOptions: [331],
    batteryCapacityKwh: 38,
    batteryKwhOptions: [38],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 130,
    features: ['15.6" Grand View Touchscreen', '135° Reclining Aero Lounge Seats'],
    whyThisFits: 'Lounge-class interior comfort with BaaS battery subscription options.',
    runningCostPerKm: 0.40,
    availability: 'available',
    imageUrl: '/explore/windsor-desktop.png',
    availableVariants: [
      { id: 'windsor-excite', name: 'Excite (38 kWh)', exShowroomPrice: 1400000, batteryCapacityKwh: 38.0, claimedRangeKm: 332, features: ['15.6" Grand View Touchscreen', 'Aero Lounge Rear Seats', 'LED DRLs'] },
      { id: 'windsor-exclusive', name: 'Exclusive (38 kWh)', exShowroomPrice: 1480000, batteryCapacityKwh: 38.0, claimedRangeKm: 332, features: ['Leatherette Interior', 'Wireless Charging', '360 View Camera'] },
      { id: 'windsor-essence', name: 'Essence (38 kWh)', exShowroomPrice: 1580000, batteryCapacityKwh: 38.0, claimedRangeKm: 332, features: ['Infinity Glass Roof', 'Multi-color Ambient Light', 'PM2.5 Air Filter'] },
    ],
  },
  {
    id: 'mg-zs-ev',
    make: 'MG Motor',
    model: 'ZS EV',
    variant: 'Exclusive Plus (50.3 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 18.98,
    priceMaxLakh: 25.44,
    exShowroomPrice: 1898000,
    effectivePrice: 1723000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 461,
    rangeKmClaimedOptions: [461],
    batteryCapacityKwh: 50.3,
    batteryKwhOptions: [50.3],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 140,
    features: ['Dual Pane Panoramic Sunroof', '360° Camera', 'i-SMART 75+ Connected Features'],
    whyThisFits: 'Proven electric SUV with luxury features and established reliability.',
    runningCostPerKm: 0.50,
    availability: 'available',
    imageUrl: '/explore/windsor-desktop.png',
  },
  {
    id: 'mg-m9-ev',
    make: 'MG Motor',
    model: 'M9 EV',
    variant: 'Presidential MPV (90 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 65.00,
    priceMaxLakh: 75.00,
    exShowroomPrice: 6500000,
    effectivePrice: 6325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 540,
    rangeKmClaimedOptions: [540],
    batteryCapacityKwh: 90,
    batteryKwhOptions: [90],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.5,
    topSpeedKmvh: 180,
    features: ['Executive Ottoman Seats', 'Massaging Rear Chairs', 'Dual Sunroofs'],
    whyThisFits: 'Ultra-luxurious VIP electric MPV designed for executive transport.',
    runningCostPerKm: 0.85,
    availability: 'available',
    imageUrl: '/explore/windsor-desktop.png',
  },
  {
    id: 'mg-cyberster',
    make: 'MG Motor',
    model: 'Cyberster',
    variant: 'AWD Roadster (77 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 65.00,
    priceMaxLakh: 72.00,
    exShowroomPrice: 6500000,
    effectivePrice: 6325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 580,
    rangeKmClaimedOptions: [580],
    batteryCapacityKwh: 77,
    batteryKwhOptions: [77],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.5,
    topSpeedKmvh: 200,
    features: ['Electric Scissor Doors', 'Soft-Top Convertible', '536 HP AWD Motor'],
    whyThisFits: 'Electric open-top sports car delivering supercar acceleration.',
    runningCostPerKm: 0.90,
    availability: 'available',
    imageUrl: '/explore/windsor-desktop.png',
  },

  // =====================================
  // HYUNDAI
  // =====================================
  {
    id: 'hyundai-creta-electric',
    make: 'Hyundai',
    model: 'Creta Electric',
    variant: 'SX Option (45 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 17.99,
    priceMaxLakh: 22.50,
    exShowroomPrice: 1799000,
    effectivePrice: 1624000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 450,
    rangeKmClaimedOptions: [450],
    batteryCapacityKwh: 45,
    batteryKwhOptions: [45],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.0,
    topSpeedKmvh: 150,
    features: ['Curved Panoramic Display', 'Hyundai SmartSense ADAS Level 2', 'Bose Audio'],
    whyThisFits: "Electric version of India's favorite mid-size SUV with proven ergonomics.",
    runningCostPerKm: 0.48,
    availability: 'available',
    imageUrl: '/explore/creta-desktop.png',
  },
  {
    id: 'hyundai-ioniq-5',
    make: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'RWD (72.6 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 46.05,
    priceMaxLakh: 48.00,
    exShowroomPrice: 4605000,
    effectivePrice: 4430000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 631,
    rangeKmClaimedOptions: [631],
    batteryCapacityKwh: 72.6,
    batteryKwhOptions: [72.6],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 185,
    features: ['800V Ultra-Fast Architecture', 'Relaxation Seats', 'V2L Exterior Adapter'],
    whyThisFits: 'Award-winning EV on dedicated E-GMP platform with 18-min fast charge.',
    runningCostPerKm: 0.60,
    availability: 'available',
    imageUrl: '/explore/creta-desktop.png',
  },
  {
    id: 'hyundai-inster',
    make: 'Hyundai',
    model: 'Inster',
    variant: 'Long Range (49 kWh)',
    category: '4W',
    bodyType: 'Micro EV',
    priceMinLakh: 11.50,
    priceMaxLakh: 14.00,
    exShowroomPrice: 1150000,
    effectivePrice: 975000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 355,
    rangeKmClaimedOptions: [355],
    batteryCapacityKwh: 49,
    batteryKwhOptions: [42, 49],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.0,
    topSpeedKmvh: 140,
    features: ['Pixel LED Lighting', 'Versatile Folding Seats', 'V2L Functionality'],
    whyThisFits: 'Charming sub-compact urban electric crossover packed with tech.',
    runningCostPerKm: 0.38,
    availability: 'available',
    imageUrl: '/explore/creta-desktop.png',
  },

  // =====================================
  // KIA
  // =====================================
  {
    id: 'kia-ev6',
    make: 'Kia',
    model: 'EV6',
    variant: 'GT-Line AWD (77.4 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 60.95,
    priceMaxLakh: 65.95,
    exShowroomPrice: 6095000,
    effectivePrice: 5920000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 708,
    rangeKmClaimedOptions: [708],
    batteryCapacityKwh: 77.4,
    batteryKwhOptions: [77.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 192,
    features: ['800V Ultra-Fast Charging', 'Meridian Sound System', 'Dual 12.3" Curved Displays'],
    whyThisFits: 'Sporty crossover delivering 708 km range and rapid 350kW charging support.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'kia-ev9',
    make: 'Kia',
    model: 'EV9',
    variant: 'GT-Line AWD (99.8 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 129.00,
    priceMaxLakh: 135.00,
    exShowroomPrice: 12900000,
    effectivePrice: 12725000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 561,
    rangeKmClaimedOptions: [561],
    batteryCapacityKwh: 99.8,
    batteryKwhOptions: [99.8],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 200,
    features: ['Swiveling 2nd Row Captain Seats', 'Digital Pattern Lighting', 'Fingerprint Module'],
    whyThisFits: 'Full-size 6-seater luxury electric SUV defining executive family travel.',
    runningCostPerKm: 0.95,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'kia-carens-clavis-ev',
    make: 'Kia',
    model: 'Carens Clavis EV',
    variant: '7-Seater Family (50 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 18.00,
    priceMaxLakh: 22.00,
    exShowroomPrice: 1800000,
    effectivePrice: 1625000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 420,
    rangeKmClaimedOptions: [420],
    batteryCapacityKwh: 50,
    batteryKwhOptions: [50],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 145,
    features: ['One-Touch Tumble 2nd Row Seats', 'Bose Premium Audio', 'Connected Car Tech'],
    whyThisFits: 'Practical 3-row family electric MPV tailored for multi-passenger journeys.',
    runningCostPerKm: 0.50,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'kia-ev5',
    make: 'Kia',
    model: 'EV5',
    variant: 'Earth Long Range (88.1 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 30.00,
    priceMaxLakh: 36.00,
    exShowroomPrice: 3000000,
    effectivePrice: 2825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [530],
    batteryCapacityKwh: 88.1,
    batteryKwhOptions: [88.1],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 185,
    features: ['Opposites United Styling', 'Refrigerated Console Drawer', 'Level 2 ADAS'],
    whyThisFits: 'Mid-size electric SUV featuring versatile modular interior layouts.',
    runningCostPerKm: 0.58,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // MARUTI SUZUKI
  // =====================================
  {
    id: 'maruti-e-vitara',
    make: 'Maruti Suzuki',
    model: 'e Vitara',
    variant: 'AllGrip e-AWD (61 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 16.00,
    priceMaxLakh: 21.00,
    exShowroomPrice: 1600000,
    effectivePrice: 1425000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 500,
    rangeKmClaimedOptions: [400, 500],
    batteryCapacityKwh: 61,
    batteryKwhOptions: [49, 61],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 160,
    features: ['HEARTECT-e Platform', 'AllGrip e-AWD', 'Dual Digital Displays'],
    whyThisFits: "Maruti's debut electric SUV engineered for widespread service support.",
    runningCostPerKm: 0.45,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'maruti-electric-mpv',
    make: 'Maruti Suzuki',
    model: 'Electric MPV',
    variant: '7-Seater Family (60 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 18.00,
    priceMaxLakh: 23.00,
    exShowroomPrice: 1800000,
    effectivePrice: 1625000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 480,
    rangeKmClaimedOptions: [480],
    batteryCapacityKwh: 60,
    batteryKwhOptions: [60],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['Spacious 3-Row Cabin', 'Roof-Mounted AC Vents', 'Smartplay Pro+ Tech'],
    whyThisFits: 'Reliable 7-seater electric MPV designed for commercial and private transport.',
    runningCostPerKm: 0.48,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },

  // =====================================
  // TOYOTA
  // =====================================
  {
    id: 'toyota-urban-cruiser-ev',
    make: 'Toyota',
    model: 'Urban Cruiser EV',
    variant: 'VX Dual Tone (61 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 17.00,
    priceMaxLakh: 22.00,
    exShowroomPrice: 1700000,
    effectivePrice: 1525000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 500,
    rangeKmClaimedOptions: [500],
    batteryCapacityKwh: 61,
    batteryKwhOptions: [61],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 160,
    features: ['Toyota Safety Sense', 'E-Four AWD Option', 'Toyota i-Connect'],
    whyThisFits: 'Robust mid-size electric SUV backed by Toyota reliability and warranty.',
    runningCostPerKm: 0.46,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
  },
  {
    id: 'toyota-bz4x',
    make: 'Toyota',
    model: 'bZ4X',
    variant: 'AWD (71.4 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 60.00,
    priceMaxLakh: 68.00,
    exShowroomPrice: 6000000,
    effectivePrice: 5825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 516,
    rangeKmClaimedOptions: [516],
    batteryCapacityKwh: 71.4,
    batteryKwhOptions: [71.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 160,
    features: ['Solar Roof Option', 'X-MODE Off-Road Control', 'JBL Premium Sound'],
    whyThisFits: 'Global electric SUV showcasing Toyota e-TNGA dedicated EV platform.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
  },

  // =====================================
  // BYD
  // =====================================
  {
    id: 'byd-atto-3',
    make: 'BYD',
    model: 'Atto 3',
    variant: 'Superior Extended (60.48 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 24.99,
    priceMaxLakh: 33.99,
    exShowroomPrice: 2499000,
    effectivePrice: 2324000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 521,
    rangeKmClaimedOptions: [468, 521],
    batteryCapacityKwh: 60.48,
    batteryKwhOptions: [49.92, 60.48],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 160,
    features: ['BYD Ultra-Safe Blade Battery', 'Rotating 15.6" Touchscreen', 'VTOL Mobile Power'],
    whyThisFits: 'Ultra-safe Blade Battery technology with premium gym-inspired interior styling.',
    runningCostPerKm: 0.52,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'byd-seal',
    make: 'BYD',
    model: 'Seal',
    variant: 'Performance AWD (82.56 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 41.00,
    priceMaxLakh: 53.00,
    exShowroomPrice: 4100000,
    effectivePrice: 3925000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 650,
    rangeKmClaimedOptions: [570, 650],
    batteryCapacityKwh: 82.56,
    batteryKwhOptions: [61.44, 82.56],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 180,
    features: ['Cell-to-Body (CTB) Tech', '0-100 km/h in 3.8s', 'iTAC Torque Control'],
    whyThisFits: 'High-performance electric sedan rivaling luxury sport saloons.',
    runningCostPerKm: 0.58,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'byd-sealion-7',
    make: 'BYD',
    model: 'Sealion 7',
    variant: 'Performance AWD (82.5 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 45.00,
    priceMaxLakh: 55.00,
    exShowroomPrice: 4500000,
    effectivePrice: 4325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 550,
    rangeKmClaimedOptions: [550],
    batteryCapacityKwh: 82.5,
    batteryKwhOptions: [82.5],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 215,
    features: ['23,000 RPM Electric Motor', '230kW Ultra-Fast DC Charging', 'Dynaudio Sound'],
    whyThisFits: 'Sleek coupe SUV with high-revolution motor performance.',
    runningCostPerKm: 0.62,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'byd-emax-7',
    make: 'BYD',
    model: 'eMAX 7',
    variant: 'Superior 6-Seater (71.8 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 26.90,
    priceMaxLakh: 29.90,
    exShowroomPrice: 2690000,
    effectivePrice: 2515000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [420, 530],
    batteryCapacityKwh: 71.8,
    batteryKwhOptions: [55.4, 71.8],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 160,
    features: ['Captains Chairs with Armrests', 'NFC Digital Key', 'Full Panoramic Glass Roof'],
    whyThisFits: 'Premium 6/7 seater electric MPV tailored for family comfort.',
    runningCostPerKm: 0.54,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'byd-dolphin',
    make: 'BYD',
    model: 'Dolphin',
    variant: 'Extended Range (60.4 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 14.00,
    priceMaxLakh: 17.00,
    exShowroomPrice: 1400000,
    effectivePrice: 1225000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 427,
    rangeKmClaimedOptions: [427],
    batteryCapacityKwh: 60.4,
    batteryKwhOptions: [44.9, 60.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 150,
    features: ['Ocean Aesthetic Design', '12.8" Rotating Screen', 'V2L Functionality'],
    whyThisFits: 'Youthful electric hatchback built on BYD e-Platform 3.0.',
    runningCostPerKm: 0.40,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // VINFAST
  // =====================================
  {
    id: 'vinfast-vf3',
    make: 'VinFast',
    model: 'VF3',
    variant: 'Base Urban (18.6 kWh)',
    category: '4W',
    bodyType: 'Micro EV',
    priceMinLakh: 8.00,
    priceMaxLakh: 10.00,
    exShowroomPrice: 800000,
    effectivePrice: 625000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 210,
    rangeKmClaimedOptions: [210],
    batteryCapacityKwh: 18.6,
    batteryKwhOptions: [18.6],
    empanelledStatus: 'verified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 100,
    features: ['Mini SUV Styling', '10" Touchscreen Display', '16" Alloy Wheels'],
    whyThisFits: 'Quirky micro electric SUV for tight inner-city commuting.',
    runningCostPerKm: 0.28,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'vinfast-vf6',
    make: 'VinFast',
    model: 'VF6',
    variant: 'Plus (59.6 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 16.00,
    priceMaxLakh: 20.00,
    exShowroomPrice: 1600000,
    effectivePrice: 1425000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 399,
    rangeKmClaimedOptions: [399],
    batteryCapacityKwh: 59.6,
    batteryKwhOptions: [59.6],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 150,
    features: ['Pininfarina Design', '12.9" Infotainment', 'Level 2 ADAS'],
    whyThisFits: 'Sub-compact SUV styled by Pininfarina with high-tech cabin.',
    runningCostPerKm: 0.46,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'vinfast-vf7',
    make: 'VinFast',
    model: 'VF7',
    variant: 'Plus Dual Motor (75.3 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 25.00,
    priceMaxLakh: 32.00,
    exShowroomPrice: 2500000,
    effectivePrice: 2325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 431,
    rangeKmClaimedOptions: [431],
    batteryCapacityKwh: 75.3,
    batteryKwhOptions: [75.3],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 190,
    features: ['AWD Dual Motor (348 HP)', 'Head-Up Display', 'Panoramic Glass Roof'],
    whyThisFits: 'Avant-garde electric SUV delivering high dual-motor performance.',
    runningCostPerKm: 0.58,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'vinfast-vf8',
    make: 'VinFast',
    model: 'VF8',
    variant: 'Plus AWD (87.7 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 35.00,
    priceMaxLakh: 42.00,
    exShowroomPrice: 3500000,
    effectivePrice: 3325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 471,
    rangeKmClaimedOptions: [471],
    batteryCapacityKwh: 87.7,
    batteryKwhOptions: [87.7],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.5,
    topSpeedKmvh: 200,
    features: ['Full Leatherette Interior', 'Smart Services App', '402 HP AWD'],
    whyThisFits: 'Mid-size luxury electric SUV equipped for long-distance cruising.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'vinfast-vf9',
    make: 'VinFast',
    model: 'VF9',
    variant: 'Plus 7-Seater (123 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 60.00,
    priceMaxLakh: 70.00,
    exShowroomPrice: 6000000,
    effectivePrice: 5825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 594,
    rangeKmClaimedOptions: [594],
    batteryCapacityKwh: 123,
    batteryKwhOptions: [123],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.5,
    topSpeedKmvh: 200,
    features: ['Massaging Captain Chairs', '15.6" Central Screen', 'Level 2 ADAS'],
    whyThisFits: 'Full-size 7-seat flagship electric SUV with huge battery capacity.',
    runningCostPerKm: 0.85,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },

  // =====================================
  // CITROËN
  // =====================================
  {
    id: 'citroen-ec3',
    make: 'Citroën',
    model: 'eC3',
    variant: 'Shine (29.2 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 11.61,
    priceMaxLakh: 13.50,
    exShowroomPrice: 1161000,
    effectivePrice: 986000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 320,
    rangeKmClaimedOptions: [320],
    batteryCapacityKwh: 29.2,
    batteryKwhOptions: [29.2],
    empanelledStatus: 'verified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 107,
    features: ['Advanced Comfort Suspension', '10" Touchscreen', 'MyCitroën Connect'],
    whyThisFits: 'Supremely plush ride quality with French comfort suspension tuned for Indian roads.',
    runningCostPerKm: 0.36,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
  },
  {
    id: 'citroen-ec3-aircross-ev',
    make: 'Citroën',
    model: 'eC3 Aircross EV',
    variant: '7-Seater Plus (44 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 14.50,
    priceMaxLakh: 17.50,
    exShowroomPrice: 1450000,
    effectivePrice: 1275000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 400,
    rangeKmClaimedOptions: [400],
    batteryCapacityKwh: 44,
    batteryKwhOptions: [44],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.0,
    topSpeedKmvh: 135,
    features: ['Flexible 5+2 Seating', 'Roof AC Vents', '10.2" Infotainment'],
    whyThisFits: 'Versatile 7-seater electric SUV offering high modularity.',
    runningCostPerKm: 0.44,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
  },

  // =====================================
  // PMV
  // =====================================
  {
    id: 'pmv-eas-e',
    make: 'PMV',
    model: 'EaS-E',
    variant: 'Smart Micro (10 kWh)',
    category: '4W',
    bodyType: 'Micro EV',
    priceMinLakh: 4.79,
    priceMaxLakh: 5.50,
    exShowroomPrice: 479000,
    effectivePrice: 329000,
    subsidyAmount: 120000,
    scrappageBonus: 15000,
    rangeKm: 160,
    rangeKmClaimedOptions: [160],
    batteryCapacityKwh: 10,
    batteryKwhOptions: [10],
    empanelledStatus: 'verified',
    chargingTimeHours: 3.0,
    topSpeedKmvh: 70,
    features: ['Feet Free Driving Mode', 'Remote Parking Assistant', 'Air Conditioning'],
    whyThisFits: 'Ultra-affordable 2-seater micro electric mobility solution.',
    runningCostPerKm: 0.20,
    availability: 'available',
    imageUrl: '/explore/curvv-ev-desktop.png',
  },

  // =====================================
  // VAYVE MOBILITY
  // =====================================
  {
    id: 'vayve-eva',
    make: 'Vayve',
    model: 'Eva',
    variant: 'Solar Roof Micro (14 kWh)',
    category: '4W',
    bodyType: 'Micro EV',
    priceMinLakh: 6.00,
    priceMaxLakh: 7.50,
    exShowroomPrice: 600000,
    effectivePrice: 450000,
    subsidyAmount: 120000,
    scrappageBonus: 15000,
    rangeKm: 250,
    rangeKmClaimedOptions: [250],
    batteryCapacityKwh: 14,
    batteryKwhOptions: [14],
    empanelledStatus: 'verified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 80,
    features: ['Integrated Solar Roof', 'Monocoque Chassis', 'AC Climate Control'],
    whyThisFits: "India's first solar-powered urban micro EV providing free solar range.",
    runningCostPerKm: 0.18,
    availability: 'available',
    imageUrl: '/explore/curvv-ev-desktop.png',
  },

  // =====================================
  // BMW
  // =====================================
  {
    id: 'bmw-i4',
    make: 'BMW',
    model: 'i4',
    variant: 'eDrive40 Gran Coupe (83.9 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 72.50,
    priceMaxLakh: 77.50,
    exShowroomPrice: 7250000,
    effectivePrice: 7075000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 590,
    rangeKmClaimedOptions: [590],
    batteryCapacityKwh: 83.9,
    batteryKwhOptions: [83.9],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.5,
    topSpeedKmvh: 190,
    features: ['BMW Curved Display', 'Harman Kardon Surround', 'iDrive 8.5 OS'],
    whyThisFits: 'Dynamic 4-door electric Gran Coupe with traditional BMW handling.',
    runningCostPerKm: 0.72,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'bmw-i5',
    make: 'BMW',
    model: 'i5',
    variant: 'M60 xDrive (81.2 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 119.50,
    priceMaxLakh: 125.00,
    exShowroomPrice: 11950000,
    effectivePrice: 11775000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 516,
    rangeKmClaimedOptions: [516],
    batteryCapacityKwh: 81.2,
    batteryKwhOptions: [81.2],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 230,
    features: ['601 HP M Performance', 'Interaction Bar', 'Air Suspension'],
    whyThisFits: 'High-performance business sedan delivering sports car speed.',
    runningCostPerKm: 0.88,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'bmw-i7',
    make: 'BMW',
    model: 'i7',
    variant: 'xDrive60 Luxury (101.7 kWh)',
    category: '4W',
    bodyType: 'Luxury Sedan',
    priceMinLakh: 203.00,
    priceMaxLakh: 250.00,
    exShowroomPrice: 20300000,
    effectivePrice: 20125000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 625,
    rangeKmClaimedOptions: [625],
    batteryCapacityKwh: 101.7,
    batteryKwhOptions: [101.7],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.5,
    topSpeedKmvh: 240,
    features: ['31.3" 8K Theatre Screen', 'Automatic Comfort Doors', 'Executive Lounge'],
    whyThisFits: 'The pinnacle of electric luxury limousine travel with 8K theatre screen.',
    runningCostPerKm: 1.10,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'bmw-ix',
    make: 'BMW',
    model: 'iX',
    variant: 'xDrive50 (111.5 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 121.00,
    priceMaxLakh: 140.00,
    exShowroomPrice: 12100000,
    effectivePrice: 11925000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 630,
    rangeKmClaimedOptions: [630],
    batteryCapacityKwh: 111.5,
    batteryKwhOptions: [111.5],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 200,
    features: ['Self-Healing Kidney Grille', 'Shy Tech Controls', 'Bowers & Wilkins Diamond Sound'],
    whyThisFits: 'Futuristic SAV designed with sustainable luxury materials.',
    runningCostPerKm: 0.95,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'bmw-ix1',
    make: 'BMW',
    model: 'iX1',
    variant: 'xDrive30 M Sport (64.7 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 66.90,
    priceMaxLakh: 69.90,
    exShowroomPrice: 6690000,
    effectivePrice: 6515000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 440,
    rangeKmClaimedOptions: [440],
    batteryCapacityKwh: 64.7,
    batteryKwhOptions: [64.7],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 180,
    features: ['Dual Motor xDrive AWD', 'BMW Curved Display', 'M Sport Body Styling'],
    whyThisFits: 'Agile luxury compact electric SAV for premium daily commuting.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // MERCEDES-BENZ
  // =====================================
  {
    id: 'mercedes-eqa',
    make: 'Mercedes-Benz',
    model: 'EQA',
    variant: '250+ AMG Line (70.5 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 66.00,
    priceMaxLakh: 70.00,
    exShowroomPrice: 6600000,
    effectivePrice: 6425000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 560,
    rangeKmClaimedOptions: [560],
    batteryCapacityKwh: 70.5,
    batteryKwhOptions: [70.5],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 160,
    features: ['MBUX Hyperscreen Aesthetics', 'Burmester Surround', 'AMG Body Styling'],
    whyThisFits: 'Compact electric luxury SUV with long 560 km range.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'mercedes-eqb',
    make: 'Mercedes-Benz',
    model: 'EQB',
    variant: '350 4MATIC 7-Seater (66.5 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 70.90,
    priceMaxLakh: 77.50,
    exShowroomPrice: 7090000,
    effectivePrice: 6915000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 447,
    rangeKmClaimedOptions: [447],
    batteryCapacityKwh: 66.5,
    batteryKwhOptions: [66.5],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 160,
    features: ['7-Seater Layout', '4MATIC All-Wheel Drive', 'Electric Art Line'],
    whyThisFits: 'Versatile 7-seater luxury electric SUV for family luxury.',
    runningCostPerKm: 0.70,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'mercedes-eqs',
    make: 'Mercedes-Benz',
    model: 'EQS',
    variant: '580 4MATIC (107.8 kWh)',
    category: '4W',
    bodyType: 'Luxury Sedan',
    priceMinLakh: 162.00,
    priceMaxLakh: 175.00,
    exShowroomPrice: 16200000,
    effectivePrice: 16025000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 857,
    rangeKmClaimedOptions: [857],
    batteryCapacityKwh: 107.8,
    batteryKwhOptions: [107.8],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.5,
    topSpeedKmvh: 210,
    features: ['56" MBUX Hyperscreen', 'Rear Axle Steering 10°', 'HEPA Air Filter'],
    whyThisFits: 'India-made luxury saloon with unbeatable 857 km certified range.',
    runningCostPerKm: 0.90,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'mercedes-eqs-suv',
    make: 'Mercedes-Benz',
    model: 'EQS SUV',
    variant: '580 4MATIC (118 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 141.00,
    priceMaxLakh: 160.00,
    exShowroomPrice: 14100000,
    effectivePrice: 13925000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 647,
    rangeKmClaimedOptions: [647],
    batteryCapacityKwh: 118,
    batteryKwhOptions: [118],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.5,
    topSpeedKmvh: 210,
    features: ['MBUX Hyperscreen', 'AIRMATIC Air Suspension', 'Off-Road Drive Mode'],
    whyThisFits: 'Ultra-flagship electric SUV combining S-Class luxury with SUV clearance.',
    runningCostPerKm: 1.05,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'mercedes-g-580-eq',
    make: 'Mercedes-Benz',
    model: 'G 580 with EQ Technology',
    variant: 'Edition 1 (116 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 300.00,
    priceMaxLakh: 350.00,
    exShowroomPrice: 30000000,
    effectivePrice: 29825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 473,
    rangeKmClaimedOptions: [473],
    batteryCapacityKwh: 116,
    batteryKwhOptions: [116],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 180,
    features: ['G-TURN 360° Tank Turn', '4 Individual Motors', 'Virtual Underbond View'],
    whyThisFits: 'Electric G-Wagon capable of on-the-spot 360-degree tank turns.',
    runningCostPerKm: 1.40,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // AUDI
  // =====================================
  {
    id: 'audi-q8-etron',
    make: 'Audi',
    model: 'Q8 e-tron',
    variant: '55 quattro (114 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 115.00,
    priceMaxLakh: 130.00,
    exShowroomPrice: 11500000,
    effectivePrice: 11325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 600,
    rangeKmClaimedOptions: [600],
    batteryCapacityKwh: 114,
    batteryKwhOptions: [114],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 200,
    features: ['Virtual Exterior Mirrors', 'Adaptive Air Suspension', 'Bang & Olufsen 3D Sound'],
    whyThisFits: 'Audi flagship electric SUV offering silent performance and air suspension.',
    runningCostPerKm: 0.92,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'audi-q6-etron',
    make: 'Audi',
    model: 'Q6 e-tron',
    variant: 'quattro (100 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 85.00,
    priceMaxLakh: 95.00,
    exShowroomPrice: 8500000,
    effectivePrice: 8325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 625,
    rangeKmClaimedOptions: [625],
    batteryCapacityKwh: 100,
    batteryKwhOptions: [100],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 210,
    features: ['PPE 800V Architecture', 'Digital OLED Tail Lights', 'Passenger Display Screen'],
    whyThisFits: 'Next-gen mid-size electric SUV built on Premium Platform Electric.',
    runningCostPerKm: 0.80,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'audi-a6-etron',
    make: 'Audi',
    model: 'A6 e-tron',
    variant: 'Performance (100 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 90.00,
    priceMaxLakh: 105.00,
    exShowroomPrice: 9000000,
    effectivePrice: 8825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 750,
    rangeKmClaimedOptions: [750],
    batteryCapacityKwh: 100,
    batteryKwhOptions: [100],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 210,
    features: ['0.21 Drag Coefficient', '270kW DC Fast Charge', 'Matrix LED Headlights'],
    whyThisFits: 'Ultra-aerodynamic executive electric saloon with 750 km range.',
    runningCostPerKm: 0.78,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'audi-etron-gt',
    make: 'Audi',
    model: 'e-tron GT',
    variant: 'quattro (93.4 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 172.00,
    priceMaxLakh: 195.00,
    exShowroomPrice: 17200000,
    effectivePrice: 17025000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 500,
    rangeKmClaimedOptions: [500],
    batteryCapacityKwh: 93.4,
    batteryKwhOptions: [93.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.5,
    topSpeedKmvh: 245,
    features: ['Launch Control 530 HP', 'All-Wheel Steering', 'Carbon Fiber Roof Option'],
    whyThisFits: 'Breathtaking electric grand tourer combining sport performance with luxury.',
    runningCostPerKm: 1.00,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'audi-rs-etron-gt',
    make: 'Audi',
    model: 'RS e-tron GT',
    variant: 'Performance (105 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 205.00,
    priceMaxLakh: 230.00,
    exShowroomPrice: 20500000,
    effectivePrice: 20325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 609,
    rangeKmClaimedOptions: [609],
    batteryCapacityKwh: 105,
    batteryKwhOptions: [105],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.5,
    topSpeedKmvh: 250,
    features: ['925 HP Boost Mode', 'Active Suspension', 'Carbon Ceramic Brakes'],
    whyThisFits: 'The most powerful production Audi ever made with 925 HP peak boost.',
    runningCostPerKm: 1.20,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // VOLVO
  // =====================================
  {
    id: 'volvo-ex30',
    make: 'Volvo',
    model: 'EX30',
    variant: 'Single Motor Extended (69 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 40.00,
    priceMaxLakh: 45.00,
    exShowroomPrice: 4000000,
    effectivePrice: 3825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 476,
    rangeKmClaimedOptions: [476],
    batteryCapacityKwh: 69,
    batteryKwhOptions: [69],
    empanelledStatus: 'verified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 180,
    features: ['Minimalist Soundbar Audio', 'Google Built-In OS', 'Recycled Interior Materials'],
    whyThisFits: 'Compact Scandinavian electric SUV with lowest carbon footprint.',
    runningCostPerKm: 0.55,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'volvo-ex40',
    make: 'Volvo',
    model: 'EX40',
    variant: 'Twin Motor AWD (82 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 56.90,
    priceMaxLakh: 62.00,
    exShowroomPrice: 5690000,
    effectivePrice: 5515000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [530],
    batteryCapacityKwh: 82,
    batteryKwhOptions: [82],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 180,
    features: ['Pixel LED Headlights', 'Harman Kardon Premium Sound', 'One-Pedal Drive'],
    whyThisFits: 'Safety-first luxury electric SUV with dual-motor power.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'volvo-ec40',
    make: 'Volvo',
    model: 'EC40',
    variant: 'Ultimate Twin AWD (82 kWh)',
    category: '4W',
    bodyType: 'Coupe',
    priceMinLakh: 62.50,
    priceMaxLakh: 66.00,
    exShowroomPrice: 6250000,
    effectivePrice: 6075000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [530],
    batteryCapacityKwh: 82,
    batteryKwhOptions: [82],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 180,
    features: ['Crossover Coupe Styling', 'Leather-Free Interior', '408 HP AWD'],
    whyThisFits: 'Stylish electric crossover coupe packed with advanced safety tech.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'volvo-ex90',
    make: 'Volvo',
    model: 'EX90',
    variant: 'Twin Motor Performance (111 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 130.00,
    priceMaxLakh: 150.00,
    exShowroomPrice: 13000000,
    effectivePrice: 12825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 600,
    rangeKmClaimedOptions: [600],
    batteryCapacityKwh: 111,
    batteryKwhOptions: [111],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 180,
    features: ['Roof-Integrated LiDAR', 'Bowers & Wilkins Dolby Atmos', '7-Seat Luxury'],
    whyThisFits: 'The safest Volvo ever created featuring roof-mounted LiDAR technology.',
    runningCostPerKm: 0.95,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // PORSCHE
  // =====================================
  {
    id: 'porsche-taycan',
    make: 'Porsche',
    model: 'Taycan',
    variant: 'Turbo S Performance (105 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 189.00,
    priceMaxLakh: 252.00,
    exShowroomPrice: 18900000,
    effectivePrice: 18725000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 630,
    rangeKmClaimedOptions: [630],
    batteryCapacityKwh: 105,
    batteryKwhOptions: [105],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 260,
    features: ['Porsche Active Ride', '952 HP Launch Control', '800V Architecture'],
    whyThisFits: 'The definitive electric sports saloon with breathtaking dynamics.',
    runningCostPerKm: 1.15,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'porsche-macan-electric',
    make: 'Porsche',
    model: 'Macan Electric',
    variant: 'Turbo Electric (100 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 165.00,
    priceMaxLakh: 185.00,
    exShowroomPrice: 16500000,
    effectivePrice: 16325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 591,
    rangeKmClaimedOptions: [591],
    batteryCapacityKwh: 100,
    batteryKwhOptions: [100],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.5,
    topSpeedKmvh: 260,
    features: ['PPE Platform', '639 HP Launch Control', 'Augmented Reality HUD'],
    whyThisFits: 'Sports car performance wrapped in a practical luxury compact SUV.',
    runningCostPerKm: 1.05,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // MINI
  // =====================================
  {
    id: 'mini-countryman-electric',
    make: 'MINI',
    model: 'Countryman Electric',
    variant: 'SE ALL4 (66.4 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 54.90,
    priceMaxLakh: 59.00,
    exShowroomPrice: 5490000,
    effectivePrice: 5315000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 433,
    rangeKmClaimedOptions: [433],
    batteryCapacityKwh: 66.4,
    batteryKwhOptions: [66.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 180,
    features: ['Circular OLED Screen', 'Go-Kart Drive Modes', 'ALL4 All-Wheel Drive'],
    whyThisFits: 'Iconic MINI go-kart feel scaled into a spacious electric crossover.',
    runningCostPerKm: 0.65,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // LOTUS
  // =====================================
  {
    id: 'lotus-eletre',
    make: 'Lotus',
    model: 'Eletre',
    variant: 'R Hyper-SUV (112 kWh)',
    category: '4W',
    bodyType: 'Luxury SUV',
    priceMinLakh: 255.00,
    priceMaxLakh: 299.00,
    exShowroomPrice: 25500000,
    effectivePrice: 25325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 600,
    rangeKmClaimedOptions: [600],
    batteryCapacityKwh: 112,
    batteryKwhOptions: [112],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.5,
    topSpeedKmvh: 265,
    features: ['905 HP Dual Motor', 'Deployable Deployable LiDAR', 'KEF Reference Audio'],
    whyThisFits: 'Hyper-electric SUV delivering supercar power and active aerodynamics.',
    runningCostPerKm: 1.30,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },
  {
    id: 'lotus-emeya',
    make: 'Lotus',
    model: 'Emeya',
    variant: 'Hyper-GT (102 kWh)',
    category: '4W',
    bodyType: 'Luxury Sedan',
    priceMinLakh: 240.00,
    priceMaxLakh: 280.00,
    exShowroomPrice: 24000000,
    effectivePrice: 23825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 610,
    rangeKmClaimedOptions: [610],
    batteryCapacityKwh: 102,
    batteryKwhOptions: [102],
    empanelledStatus: 'verified',
    chargingTimeHours: 8.0,
    topSpeedKmvh: 256,
    features: ['Active Front Grille', 'Dual-Layer Rear Spoiler', 'Electronically Controlled Air Suspension'],
    whyThisFits: 'Hyper-electric GT saloon engineered for ultimate high-speed stability.',
    runningCostPerKm: 1.25,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // LEXUS
  // =====================================
  {
    id: 'lexus-rz',
    make: 'Lexus',
    model: 'RZ',
    variant: '450e Luxury AWD (71.4 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 85.00,
    priceMaxLakh: 95.00,
    exShowroomPrice: 8500000,
    effectivePrice: 8325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 435,
    rangeKmClaimedOptions: [435],
    batteryCapacityKwh: 71.4,
    batteryKwhOptions: [71.4],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 160,
    features: ['DIRECT4 AWD Control', 'Steer-by-Wire Option', 'Dimming Panoramic Roof'],
    whyThisFits: 'Impeccable Takumi craftsmanship in a whisper-quiet electric crossover.',
    runningCostPerKm: 0.78,
    availability: 'available',
    imageUrl: '/hero-ev-car.png',
  },

  // =====================================
  // ROLLS-ROYCE
  // =====================================
  {
    id: 'rolls-royce-spectre',
    make: 'Rolls-Royce',
    model: 'Spectre',
    variant: 'Bespoke Coupe (102 kWh)',
    category: '4W',
    bodyType: 'Luxury Sedan',
    priceMinLakh: 750.00,
    priceMaxLakh: 900.00,
    exShowroomPrice: 75000000,
    effectivePrice: 74825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [530],
    batteryCapacityKwh: 102,
    batteryKwhOptions: [102],
    empanelledStatus: 'verified',
    chargingTimeHours: 9.0,
    topSpeedKmvh: 250,
    features: ['Starlight Doors', 'Planar Suspension', 'Illuminated Pantheon Grille'],
    whyThisFits: 'The ultimate luxury electric super coupe on earth.',
    runningCostPerKm: 2.20,
    availability: 'available',
    imageUrl: '/hero-slide-3.jpg',
  },

  // =====================================
  // TESLA
  // =====================================
  {
    id: 'tesla-model-3',
    make: 'Tesla',
    model: 'Model 3',
    variant: 'Long Range AWD (75 kWh)',
    category: '4W',
    bodyType: 'Sedan',
    priceMinLakh: 45.00,
    priceMaxLakh: 55.00,
    exShowroomPrice: 4500000,
    effectivePrice: 4325000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 629,
    rangeKmClaimedOptions: [629],
    batteryCapacityKwh: 75,
    batteryKwhOptions: [60, 75],
    empanelledStatus: 'verified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 201,
    features: ['Full Self-Driving Capability', 'Acoustic Glass', 'Rear Passenger Touchscreen'],
    whyThisFits: "The world's standard electric saloon with Supercharger ecosystem access.",
    runningCostPerKm: 0.52,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
  {
    id: 'tesla-model-y',
    make: 'Tesla',
    model: 'Model Y',
    variant: 'Long Range AWD (78.1 kWh)',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 50.00,
    priceMaxLakh: 60.00,
    exShowroomPrice: 5000000,
    effectivePrice: 4825000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 533,
    rangeKmClaimedOptions: [533],
    batteryCapacityKwh: 78.1,
    batteryKwhOptions: [60, 78.1],
    empanelledStatus: 'verified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 217,
    features: ['2,100+ Liters Cargo Space', 'Autopilot Tech', 'Glass Roof'],
    whyThisFits: "The world's best-selling car, combining massive luggage space with range.",
    runningCostPerKm: 0.58,
    availability: 'available',
    imageUrl: '/hero-slide-2.png',
  },
];
