import { EmpanelledVehicle } from '@/types';

export interface UpcomingVehicle {
  make: string;
  model: string;
  note: string;
}

export const UPCOMING_2026_VEHICLES: UpcomingVehicle[] = [
  { make: 'Toyota', model: 'Urban Cruiser EV / Ebella', note: 'e-Vitara-based, expected late 2026, mid-size SUV' },
  { make: 'Mahindra', model: 'BE 07 / XEV 7e', note: '7-seat EV, expected Q1 2026' },
  { make: 'Tata Motors', model: 'Safari EV', note: 'Diwali 2026 launch, Acti.ev+ platform' },
  { make: 'Citroën', model: 'Basalt EV', note: 'Expected late 2026, estimated ₹14-17 Lakh' },
  { make: 'Hyundai', model: 'Kona Electric (facelift)', note: 'Estimated Nov 2026, ₹24.75-25.75 Lakh' },
  { make: 'MG Motor', model: 'ZS EV (facelift)', note: 'Expected late 2026' },
  { make: 'VinFast', model: 'VF3', note: 'Micro EV, estimated ~₹10 Lakh' },
];

export const SEEDED_VEHICLES_MASTER: EmpanelledVehicle[] = [
  {
    id: 'tata-tiago-ev',
    make: 'Tata Motors',
    model: 'Tiago EV',
    variant: '2026 Facelift (19.2 - 24 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 6.99,
    priceMaxLakh: 9.99,
    exShowroomPrice: 699000,
    effectivePrice: 509000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 285,
    rangeKmClaimedOptions: [226, 285],
    batteryCapacityKwh: 24,
    batteryKwhOptions: [19.2, 24],
    empanelledStatus: 'unverified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 120,
    features: ['City/Sport Drive Modes', 'ZConnect Connected Car', 'Smartwatch Integration', 'Multi-mode Regen'],
    whyThisFits: 'Ultra-accessible urban electric hatchback for daily commute in NCT Delhi.',
    runningCostPerKm: 0.28,
    availability: 'available',
    launchNote: '2026 facelift launched May 28, 2026',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-tigor-ev',
    make: 'Tata Motors',
    model: 'Tigor EV',
    variant: 'XZ+ (26 kWh)',
    category: '4W',
    bodyType: 'Compact Sedan',
    priceMinLakh: 12.49,
    priceMaxLakh: 13.75,
    exShowroomPrice: 1249000,
    effectivePrice: 974000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 315,
    rangeKmClaimedOptions: [315],
    batteryCapacityKwh: 26,
    batteryKwhOptions: [26],
    empanelledStatus: 'unverified',
    chargingTimeHours: 4.0,
    topSpeedKmvh: 120,
    features: ['ZConnect Connected Apps', '7" Touchscreen Infotainment', 'Automatic Climate Control', 'Dual Airbags'],
    whyThisFits: 'Spacious electric compact sedan suited for family transport and low maintenance.',
    runningCostPerKm: 0.35,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-punch-ev',
    make: 'Tata Motors',
    model: 'Punch EV',
    variant: 'Empowered+ LR (35 kWh)',
    category: '4W',
    bodyType: 'Micro/Sub-compact SUV',
    priceMinLakh: 9.69,
    priceMaxLakh: 12.59,
    exShowroomPrice: 969000,
    effectivePrice: 744000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 421,
    rangeKmClaimedOptions: [315, 421],
    batteryCapacityKwh: 35,
    batteryKwhOptions: [25, 35],
    empanelledStatus: 'unverified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 140,
    features: ['acti.ev Architecture', '10.25" Cinematic Screen', 'Electronic Parking Brake', '360° Camera'],
    whyThisFits: 'Highest rated sub-compact SUV with high ground clearance for Delhi NCR roads.',
    runningCostPerKm: 0.42,
    availability: 'available',
    launchNote: '2026 facelift edition',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-nexon-ev',
    make: 'Tata Motors',
    model: 'Nexon EV',
    variant: 'Empowered+ 45 (45 kWh)',
    category: '4W',
    bodyType: 'Sub-compact SUV',
    priceMinLakh: 12.49,
    priceMaxLakh: 17.69,
    exShowroomPrice: 1249000,
    effectivePrice: 974000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 489,
    rangeKmClaimedOptions: [275, 390, 489],
    batteryCapacityKwh: 45,
    batteryKwhOptions: [30, 40.5, 45],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['V2L & V2V Charging', 'Arc.ev Suite', '12.3" Display', 'JBL Audio System'],
    whyThisFits: 'India benchmark sub-compact SUV with maximum real-world highway & city range.',
    runningCostPerKm: 0.95,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-curvv-ev',
    make: 'Tata Motors',
    model: 'Curvv EV',
    variant: 'Empowered+ 55 (55 kWh)',
    category: '4W',
    bodyType: 'Coupe SUV',
    priceMinLakh: 16.99,
    priceMaxLakh: 22.24,
    exShowroomPrice: 1699000,
    effectivePrice: 1374000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 502,
    rangeKmClaimedOptions: [430, 502],
    batteryCapacityKwh: 55,
    batteryKwhOptions: [45, 55],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 160,
    features: ['Gesture Powered Tailgate', 'Panoramic Sunroof', 'Level 2 ADAS', 'Arc.ev Suite'],
    whyThisFits: 'Aerodynamic coupe styling with 55 kWh pack for intercity highway cruising.',
    runningCostPerKm: 0.92,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-sierra-ev',
    make: 'Tata Motors',
    model: 'Sierra EV',
    variant: 'AWD Flagship (75 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 18.79,
    priceMaxLakh: 26.48,
    exShowroomPrice: 1879000,
    effectivePrice: 1554000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 665,
    rangeKmClaimedOptions: [565, 665],
    batteryCapacityKwh: 75,
    batteryKwhOptions: [63, 75],
    empanelledStatus: 'unverified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 165,
    features: ['Dual-motor AWD', 'Alpine Glass Sunroof', 'Arc.ev Suite', 'V2L V2V Hub'],
    whyThisFits: 'Iconic reimagined mid-size SUV with massive 75 kWh battery option.',
    runningCostPerKm: 0.98,
    availability: 'available',
    launchNote: 'Launched June 30, 2026; deliveries from July 15, 2026',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'tata-harrier-ev',
    make: 'Tata Motors',
    model: 'Harrier EV',
    variant: 'Empowered AWD (75 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 21.49,
    priceMaxLakh: 30.43,
    boundaryModel: true,
    boundaryNote: 'Base variants under ₹30L; top trims exceed. Filter at variant level.',
    exShowroomPrice: 2149000,
    effectivePrice: 1824000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 627,
    rangeKmClaimedOptions: [627],
    batteryCapacityKwh: 75,
    batteryKwhOptions: [65, 75],
    empanelledStatus: 'unverified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 170,
    features: ['Dual Motor All-Wheel Drive', 'Vehicle-to-Load Power Out', 'Terrain Response Modes', 'L2 ADAS'],
    whyThisFits: 'Heavy-duty electric SUV with long-range battery and all-wheel drive capability.',
    runningCostPerKm: 1.05,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mahindra-xuv400',
    make: 'Mahindra',
    model: 'XUV400',
    variant: 'EL Pro (39.4 kWh)',
    category: '4W',
    bodyType: 'Compact SUV',
    priceMinLakh: 15.49,
    priceMaxLakh: 15.49,
    exShowroomPrice: 1549000,
    effectivePrice: 1224000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 456,
    rangeKmClaimedOptions: [359, 456],
    batteryCapacityKwh: 39.4,
    batteryKwhOptions: [34.5, 39.4],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['Dual 10.25" Screens', 'AdrenoX Connected Car', 'Fastest 0-100 in segment', 'Wireless Apple CarPlay'],
    whyThisFits: 'Spacious electric SUV with quick acceleration performance.',
    runningCostPerKm: 0.92,
    availability: 'being_phased_out',
    launchNote: 'Heavy discounts early 2026; being replaced by XUV 3XO EV.',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mahindra-xuv-3xo-ev',
    make: 'Mahindra',
    model: 'XUV 3XO EV',
    variant: 'AX7L (39.4 kWh)',
    category: '4W',
    bodyType: 'Sub-compact SUV',
    priceMinLakh: 13.89,
    priceMaxLakh: 13.89,
    exShowroomPrice: 1389000,
    effectivePrice: 1064000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 456,
    rangeKmClaimedOptions: [456],
    batteryCapacityKwh: 39.4,
    batteryKwhOptions: [34.5, 39.4],
    empanelledStatus: 'unverified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 145,
    features: ['Skyroof', 'Dual 10.25" Touchscreens', 'Level 2 ADAS', 'Harmon Kardon Audio'],
    whyThisFits: 'Feature-rich sub-compact SUV with optional 7.2 kW wall charger.',
    runningCostPerKm: 0.89,
    availability: 'available',
    launchNote: 'Launched Feb 2026; deliveries from Feb 23, 2026.',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mahindra-be-6',
    make: 'Mahindra',
    model: 'BE 6',
    variant: 'Pack 79 kWh',
    category: '4W',
    bodyType: 'Coupe SUV',
    priceMinLakh: 18.90,
    priceMaxLakh: 26.90,
    exShowroomPrice: 1890000,
    effectivePrice: 1565000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 682,
    rangeKmClaimedOptions: [557, 682],
    batteryCapacityKwh: 79,
    batteryKwhOptions: [59, 79],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 175,
    features: ['INGLO Architecture', 'Halo Headlamps', 'Lifetime HV Battery Warranty (1st owner)', 'HUD Screen'],
    whyThisFits: 'Next-gen electric coupe SUV with lifetime battery warranty protection.',
    runningCostPerKm: 0.94,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mahindra-xev-9e',
    make: 'Mahindra',
    model: 'XEV 9e',
    variant: 'Cineluxe (79 kWh)',
    category: '4W',
    bodyType: 'Mid-size Coupe SUV',
    priceMinLakh: 21.90,
    priceMaxLakh: 30.50,
    boundaryModel: true,
    boundaryNote: 'Base variant under ₹30L; Cineluxe edition close to ceiling. Filter at variant level.',
    exShowroomPrice: 2190000,
    effectivePrice: 1865000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 656,
    rangeKmClaimedOptions: [542, 656],
    batteryCapacityKwh: 79,
    batteryKwhOptions: [59, 79],
    empanelledStatus: 'unverified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 180,
    features: ['Triple Display Cockpit', '16-Speaker Dolby Atmos', 'Semi-Active Suspension', 'INGLO Platform'],
    whyThisFits: 'Luxury EV crossover cabin with triple-screen display cockpit.',
    runningCostPerKm: 1.02,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mahindra-xev-9s',
    make: 'Mahindra',
    model: 'XEV 9S',
    variant: 'Pack 79 kWh',
    category: '4W',
    bodyType: 'SUV',
    priceMinLakh: 19.95,
    priceMaxLakh: 19.95,
    exShowroomPrice: 1995000,
    effectivePrice: 1670000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 679,
    rangeKmClaimedOptions: [521, 679],
    batteryCapacityKwh: 79,
    batteryKwhOptions: [59, 70, 79],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 170,
    features: ['Panoramic Glass Roof', 'Level 2+ ADAS', 'Fast DC Charging (175 kW)', 'INGLO Tech'],
    whyThisFits: 'Spacious electric SUV with versatile battery capacity options.',
    runningCostPerKm: 0.96,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mg-comet-ev',
    make: 'MG Motor',
    model: 'Comet EV',
    variant: 'Exclusive / Blackstorm (17.3 kWh)',
    category: '4W',
    bodyType: 'Micro Hatchback',
    priceMinLakh: 7.80,
    priceMaxLakh: 10.07,
    exShowroomPrice: 780000,
    effectivePrice: 605000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 230,
    rangeKmClaimedOptions: [230],
    batteryCapacityKwh: 17.3,
    batteryKwhOptions: [17.3],
    empanelledStatus: 'unverified',
    chargingTimeHours: 3.5,
    topSpeedKmvh: 100,
    features: ['Dual 10.25" Screens', 'i-SMART Connectivity', 'Wireless Apple CarPlay', 'Reverse Camera'],
    whyThisFits: 'Ultra-compact 2-door micro hatchback for effortless congested city parking.',
    runningCostPerKm: 0.22,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'mg-windsor-ev',
    make: 'MG Motor',
    model: 'Windsor EV',
    variant: 'Essence Pro (52.9 kWh)',
    category: '4W',
    bodyType: 'Crossover CUV',
    priceMinLakh: 14.00,
    priceMaxLakh: 18.10,
    exShowroomPrice: 1400000,
    effectivePrice: 1075000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 449,
    rangeKmClaimedOptions: [331, 449],
    batteryCapacityKwh: 52.9,
    batteryKwhOptions: [38, 52.9],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 140,
    features: ['135° Aero Lounge Recline Seats', '15.6" Grand Touchscreen', 'Glass Aero Lounge Roof', 'BaaS Subscription Available'],
    whyThisFits: "India's best-selling EV crossover with lounge recline seating & optional BaaS subscription.",
    runningCostPerKm: 0.88,
    availability: 'available',
    baasAvailable: true,
    baasPriceLakh: 9.99,
    baasRentalPerKm: { base: 3.9, pro: 4.5 },
    dataSourceDate: '2026-07',
  },
  {
    id: 'mg-zs-ev',
    make: 'MG Motor',
    model: 'ZS EV',
    variant: 'Exclusive Plus (50.3 kWh)',
    category: '4W',
    bodyType: 'Compact SUV',
    priceMinLakh: 17.99,
    priceMaxLakh: 20.75,
    exShowroomPrice: 1799000,
    effectivePrice: 1474000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 461,
    rangeKmClaimedOptions: [461],
    batteryCapacityKwh: 50.3,
    batteryKwhOptions: [50.3],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 155,
    features: ['5-star Global NCAP Rating', 'Dual Pane Sunroof', 'Digital Bluetooth Key', 'i-SMART 75+ Features'],
    whyThisFits: 'Proven global 5-star NCAP rated compact SUV.',
    runningCostPerKm: 0.94,
    availability: 'available_may_be_discontinued',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'maruti-e-vitara',
    make: 'Maruti Suzuki',
    model: 'e Vitara',
    variant: 'Alpha Dual Tone (61 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 15.99,
    priceMaxLakh: 20.01,
    exShowroomPrice: 1599000,
    effectivePrice: 1274000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 543,
    rangeKmClaimedOptions: [440, 543],
    batteryCapacityKwh: 61,
    batteryKwhOptions: [49, 61],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['5-star Bharat NCAP', 'Level 2 ADAS', '7 Airbags', 'ALLGRIP e-AWD Option'],
    whyThisFits: 'Maruti first electric SUV backed by widespread India service network.',
    runningCostPerKm: 0.90,
    availability: 'available',
    launchNote: 'Launched Feb 17, 2026',
    baasAvailable: true,
    baasPriceLakh: 10.99,
    baasRentalPerKm: 3.99,
    dataSourceDate: '2026-07',
  },
  {
    id: 'hyundai-creta-electric',
    make: 'Hyundai',
    model: 'Creta Electric',
    variant: 'Excellence LR (51.4 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 18.02,
    priceMaxLakh: 24.70,
    exShowroomPrice: 1802000,
    effectivePrice: 1477000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 510,
    rangeKmClaimedOptions: [473, 510],
    batteryCapacityKwh: 51.4,
    batteryKwhOptions: [42, 51.4],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 160,
    features: ['171 HP Electric Motor', 'Dual 10.25" Screens', 'Hyundai SmartSense ADAS', 'V2L Power Hub'],
    whyThisFits: 'Electric variant of India favorite SUV with long-range battery & strong performance.',
    runningCostPerKm: 0.93,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'kia-syros-ev',
    make: 'Kia',
    model: 'Syros EV',
    variant: 'HTX+ / X-Line (51.4 kWh)',
    category: '4W',
    bodyType: 'Sub-compact SUV',
    priceMinLakh: 13.49,
    priceMaxLakh: 19.99,
    exShowroomPrice: 1349000,
    effectivePrice: 1024000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 526,
    rangeKmClaimedOptions: [443, 526],
    batteryCapacityKwh: 51.4,
    batteryKwhOptions: [42, 51.4],
    empanelledStatus: 'unverified',
    chargingTimeHours: 5.5,
    topSpeedKmvh: 150,
    features: ['15-Year Battery Warranty', 'Level 2 ADAS', 'BaaS Battery Subscription', 'Dual Curved Displays'],
    whyThisFits: 'Premium sub-compact electric SUV with 15-year battery warranty coverage.',
    runningCostPerKm: 0.85,
    availability: 'available',
    launchNote: 'Launched July 23, 2026; deliveries July 30, 2026',
    baasAvailable: true,
    baasPriceLakh: 7.99,
    baasRentalPerKm: 3.8,
    dataSourceDate: '2026-07',
  },
  {
    id: 'kia-carens-clavis-ev',
    make: 'Kia',
    model: 'Carens Clavis EV',
    variant: 'X-Line 7-Seater (51.4 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 17.99,
    priceMaxLakh: 25.00,
    exShowroomPrice: 1799000,
    effectivePrice: 1474000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 490,
    rangeKmClaimedOptions: [404, 490],
    batteryCapacityKwh: 51.4,
    batteryKwhOptions: [42, 51.4],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 150,
    features: ['6/7 Seater Configurable MPV', 'BaaS Option (₹12.84L + ₹3.3/km)', 'Level 2 ADAS', 'Ventilated Seats'],
    whyThisFits: 'Spacious 3-row family electric MPV with optional BaaS subscription.',
    runningCostPerKm: 0.91,
    availability: 'available',
    baasAvailable: true,
    baasPriceLakh: 12.84,
    baasRentalPerKm: 3.3,
    dataSourceDate: '2026-07',
  },
  {
    id: 'byd-atto-3',
    make: 'BYD',
    model: 'Atto 3',
    variant: 'Superior (60.48 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 24.99,
    priceMaxLakh: 34.49,
    boundaryModel: true,
    boundaryNote: 'Base variants under ₹30L; higher trims exceed. Filter at variant level.',
    exShowroomPrice: 2499000,
    effectivePrice: 2174000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 521,
    rangeKmClaimedOptions: [468, 521],
    batteryCapacityKwh: 60.48,
    batteryKwhOptions: [49.92, 60.48],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 160,
    features: ['BYD Blade Battery Tech', '12.8" Rotating Screen', '5-star Euro NCAP', 'V2L Capability'],
    whyThisFits: 'Ultra-safe BYD Blade battery technology with premium interior.',
    runningCostPerKm: 0.96,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'byd-emax-7',
    make: 'BYD',
    model: 'eMax 7',
    variant: 'Comfort 7-Seater (71.8 kWh)',
    category: '4W',
    bodyType: 'MPV',
    priceMinLakh: 26.90,
    priceMaxLakh: 29.90,
    exShowroomPrice: 2690000,
    effectivePrice: 2365000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 530,
    rangeKmClaimedOptions: [420, 530],
    batteryCapacityKwh: 71.8,
    batteryKwhOptions: [55.4, 71.8],
    empanelledStatus: 'unverified',
    chargingTimeHours: 7.0,
    topSpeedKmvh: 160,
    features: ['BYD Blade Battery Pack', '6/7 Captain Seats', 'V2L Power Hub', '12.8" Rotating Touchscreen'],
    whyThisFits: 'Luxury 3-row electric family MPV with long-range Blade battery.',
    runningCostPerKm: 0.99,
    availability: 'available',
    launchNote: 'Comfort variant with upgraded 71.8 kWh battery introduced July 2026.',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'vinfast-vf6',
    make: 'VinFast',
    model: 'VF6',
    variant: 'Plus (59.6 kWh)',
    category: '4W',
    bodyType: 'Compact SUV',
    priceMinLakh: 18.19,
    priceMaxLakh: 20.09,
    exShowroomPrice: 1819000,
    effectivePrice: 1494000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 468,
    rangeKmClaimedOptions: [463, 468],
    batteryCapacityKwh: 59.6,
    batteryKwhOptions: [59.6],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.0,
    topSpeedKmvh: 155,
    features: ['5-star Bharat NCAP Safety', 'Level 2 ADAS', 'Pininfarina Design Studio Body', '12.9" Touchscreen'],
    whyThisFits: 'Locally manufactured electric SUV (Thoothukudi plant) with Pininfarina styling.',
    runningCostPerKm: 0.92,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'vinfast-vf7',
    make: 'VinFast',
    model: 'VF7',
    variant: 'Plus AWD (75.3 kWh)',
    category: '4W',
    bodyType: 'Mid-size SUV',
    priceMinLakh: 22.99,
    priceMaxLakh: 28.09,
    exShowroomPrice: 2299000,
    effectivePrice: 1974000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 532,
    rangeKmClaimedOptions: [438, 532],
    batteryCapacityKwh: 75.3,
    batteryKwhOptions: [59.6, 75.3],
    empanelledStatus: 'unverified',
    chargingTimeHours: 6.5,
    topSpeedKmvh: 175,
    features: ['Dual Motor AWD System', '5-star Bharat NCAP', 'Head-Up Display', '12.9" Touchscreen'],
    whyThisFits: 'Mid-size performance EV with dual motor all-wheel drive option.',
    runningCostPerKm: 1.01,
    availability: 'available',
    baasAvailable: false,
    dataSourceDate: '2026-07',
  },
  {
    id: 'citroen-ec3x',
    make: 'Citroën',
    model: 'ë-C3 / eC3X',
    variant: 'Shine 2026 (29.2 kWh)',
    category: '4W',
    bodyType: 'Hatchback',
    priceMinLakh: 11.99,
    priceMaxLakh: 13.41,
    exShowroomPrice: 1199000,
    effectivePrice: 924000,
    subsidyAmount: 150000,
    scrappageBonus: 25000,
    rangeKm: 325,
    rangeKmClaimedOptions: [320, 325],
    batteryCapacityKwh: 29.2,
    batteryKwhOptions: [29.2],
    empanelledStatus: 'unverified',
    chargingTimeHours: 4.5,
    topSpeedKmvh: 107,
    features: ['Advanced Comfort Suspension', '10.2" Touchscreen Infotainment', 'BaaS Option Available (₹6.89L + ₹2.26/km)', 'Tropicalized Battery Thermal Management'],
    whyThisFits: 'Comfortable French crossover hatchback with BaaS battery subscription option.',
    runningCostPerKm: 0.38,
    availability: 'available',
    launchNote: '2026 eC3X update launched June 17, 2026',
    baasAvailable: true,
    baasPriceLakh: 6.89,
    baasRentalPerKm: 2.26,
    dataSourceDate: '2026-07',
  },
];
